cloudtools/troposphere

examples/DynamoDB_Table.py, examples/DynamoDb_Table_With_GlobalSecondaryIndex.py, troposphere/dynamodb.py
I'm not sure this is complete, but I thought someone might find it useful.
This PR adds support for GlobalSecondaryIndexes & LocalSecondaryIndexes to the dynamo db feature.
To achieve this i had to make the KeySchema section comply with the current [spec](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-keyschema).
=> Adding gsi and lsi functionality

tests/test_asg.py, troposphere/autoscaling.py
Makes InstanceId and LaunchConfigurationName mutually exclusive, and
conditionally requires one or the other.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-instanceid
=> Fixes #158

troposphere/ec2.py
This is in accordance with http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-template.html.
=> Added Encrypted option to EBSBlockDevice property

examples/Autoscaling.py, tests/test_basic.py, tests/test_policies.py, troposphere/autoscaling.py
Fixes validation using UpdatePolicy introduced to 0.7.0, which had an API-breaking change, but didn't update validation. Also removed the root UpdatePolicy class so not to lead to confusion.
Without this, any use of the new UpdatePolicy will fail to serialize to JSON.
=> Fixing UpdatePolicy validation

examples/CloudFormation_Init_ConfigSet.py, tests/examples_output/CloudFormation_Init_ConfigSet.template, troposphere/autoscaling.py, troposphere/cloudformation.py
Current CFN Init capabilities only allow for a single "config" property
on the `cloudformation.Init` class. This PR adds support for configSets
according to:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
Took some of what @mbrossard had in #70 and ran with it.
=> Adding AWS::CloudFormation::Init ConfigSets support

scripts/cfn2py
Hi,
I improved cfn2py to the point where it can roundtrip the examples (except for the OpenStack examples). It also works with some private files that include AWS::CloudFormation::Init sections.
Though not perfect and not used every day, cfn2py was my gateway to using troposphere. I think these improvements might help the next future users to step onboard.
To test with the examples, I used the following script:
```bash
#!/bin/sh
if ! [ -d tmp ] ; then mkdir tmp ; fi
for i in examples/*.py ; do
BASE=tmp/`basename $i .py`
if python $i >$BASE.json1 2>&1 ; then
echo $i;
./scripts/cfn2py $BASE.json1 > $BASE.py ;
python $BASE.py > $BASE.json2 ;
cmp $BASE.json1 $BASE.json2
fi
done
```
Sincerely,
Mathias Brossard
PS: I haven't coded much in Python, so there is probably some room for improvement.
=> Improved cfn2py

troposphere/__init__.py
Hi,
I found some places were a list of basestring is expected but where a Ref function call would be used (e.g. the buckets value in an AuthenticationBlock). This is similar to what we do a few line above for a non-list type.
Sincerely,
--
Mathias
=> Support AWS helper functions in lists during validation

troposphere/autoscaling.py
StartTime and EndTime are not required Parameters according to AWS
Documentation:
http://amzn.to/1uPqyqd
=> Change AutoScaling ScheduledAction StartTime and EndTime to False

troposphere/ec2.py
I'm going through some our scripts so I'll PR what I find wrong, mostly required parameters missing
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-security-group-egress.html#cfn-ec2-securitygroupegress-groupid
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpn-gatewayrouteprop.html#cfn-ec2-vpngatewayrouteprop-routetableids
=> add ec2 required fields

troposphere/elasticache.py
According to the latest docs for `Elasticache` the `VpcSecurityGroupIds` is `GetAtt` from the `SecurityGroup` not `Ref`.
I've left `Ref` as not to break people that are using it.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#cfn-elasticache-cachecluster-vpcsecuritygroupids
=> Elasticache VpcSecurityGroupIds should accept GetAtt

troposphere/iam.py
I guess I sort of broke backwards compatibility by making 'Policy' the Resource, and PolicyProperty the property.  I can change that back, but it made sense to me.  Let me know if you guys think otherwise.
=> Clear up Policy Resource vs Policy Property

troposphere/cloudfront.py
Origin object is missing OriginPath attribute, as described here: http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/DistributionConfigDatatype.html
=> Missing OriginPath in cloudfront.py

tests/test_rds.py, troposphere/rds.py
Based on (http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-sourcedbinstanceidentifier) ``BackupRetentionPeriod``, ``DBName``, ``MasterUsername``, ``MasterUserPassword``, ``PreferredBackupWindow``, ``MultiAZ`` and ``DBSnapshotIdentifier`` can't be present when ``SourceDBInstanceIdentifier`` is specified.
Although CloudFormation validator doesn't fail, manual tests have proven that ``DBSubnetGroupName`` can't be present if ``SourceDBInstanceIdentifier`` is specified.
I've successfully deployed several read-replicas using this code.
=> Fix DBInstance constraints in order to allow the creation of RDS read-only replicas

tests/test_rds.py, troposphere/rds.py
See yesterday's AWS announcement for the new properties: [AWS CloudFormation Updates Support for RDS, EBS, and ElastiCache](https://aws.amazon.com/about-aws/whats-new/2015/04/aws-cloudformation-updates-support-for-rds-ebs-and-elasticache/) and the current [CloudFormation User Guide](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-ug.pdf).
=> Add properties CharacterSetName, KmsKeyId, and StorageEncrypted to AWS::RDS::DBInstance

examples/IAM_Users_Groups_and_Policies.py, tests/examples_output/IAM_Users_Groups_and_Policies.template
this brings the example in line with
https://s3.amazonaws.com/cloudformation-templates-us-east-1/IAM_Users_Groups_and_Policies.template
The current example CFN template will fail if you try to create-stack (I modified it for my use and found this bug).  
FYI I wrote a test harness to validate the example templates against the AWS CLI, but the validate-template does not catch this bug.  Let me know if you're interested in having this test harness, unfortunately it introduces a need for the AWS CLI and real IAM credentials that has `cloudformation:ValidateTemplate` rights, so it might be too heavy to be useful.
=> examples fix: users is list

troposphere/sns.py
Believe it or not, none of the SNS Topic fields are required. If nothing ...is specified, CF will generate a new based on the name of the stack.
This PR gets the definition matching the Doc:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
=> SNS Topic fields are not required

CHANGELOG.md, tests/test_asg.py, tests/test_policies.py, troposphere/autoscaling.py
Currently, when creating an `AutoScalingGroup` object, the `AvailabilityZones` parameter is required. However, the [AWS documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-availabilityzones) states: `Required: Conditional. If you don't specify the VPCZoneIdentifier property, you must specify this property.`
This change makes the `AvailabilityZones` parameter optional.
=> Make AvailabilityZones parameter optional in AutoScalingGroup

CHANGELOG.md, troposphere/__init__.py
Per:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html
You no longer need (not sure if you needed to before) to provide a
region to Fn::GetAZs.  This should allow that.
=> Allows default region when not provided

README.rst
Fixes GH-235
InstanceType is no longer required:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-instancetype
=> Fix incorrect Instance README example

troposphere/elasticache.py
Regarding the `AZMode` property on CacheCluster objects, the [AWS documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#cfn-elasticache-cachecluster-azmode) states :
```
If you specify multiple Availability Zones in the PreferredAvailabilityZones
property, you must specify cross Availability Zones for this property.
```
This patch introduces validation on the CacheCluster object and ensures that `AZMode` is set to `cross-az` if more than one Availability Zone is specified in the `PreferredAvailabilityZones` property.
=> Add validation for AZMode property on CacheCluster objects

troposphere/opsworks.py
Amazon expects "ThresholdsWaitTime", not "ThresholdWaitTime".
=> Fixing Opsworks Naming

troposphere/datapipeline.py, troposphere/ecs.py, troposphere/elasticache.py, troposphere/iam.py, troposphere/lambda.py, troposphere/rds.py, troposphere/s3.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/DocumentHistory.html
=> Release June 11, 2015

troposphere/ec2.py
Noticed this feature existed in the [CloudFormation Docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html) but not here, so I added it! Simplest change ever :)
=> Add property for Subnet: MapPublicIpOnLaunch

.gitignore, .travis.yml, README.rst, examples/CustomResource.py, tests/examples_output/CustomResource.template, troposphere/__init__.py, troposphere/cloudformation.py
CustomResource added - I've used it in my own work and found that it's great for implementing resource types currently not supported by CloudFormation (for instance PlacementGroup's).
Known limitations: The CustomResource properties are not checked.
It's my first PR, so I very well might have missed something.
=> CustomResource including example, updated todo in readme

examples/RDS_Snapshot_On_Delete.py, tests/examples_output/RDS_Snapshot_On_Delete.template
This PR adds an example for Amazon RDS DB instance with a deletion policy as follows.
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/sample-templates-services-us-west-2.html
* https://s3-us-west-2.amazonaws.com/cloudformation-templates-us-west-2/RDS_Snapshot_On_Delete.template
=> Add rds snapshot on delete example

troposphere/elasticache.py
If PreferredAvailabilityZones is an If or some other conditional, this validation is invalid, so skip it unless PreferredAvailabilityZones is a list.
Example:
```
t = Template()
number_cache_nodes = t.add_parameter(...)
t.add_condition("HasOneCache", Equals(
Ref(number_cache_nodes),
"1"
))
ec = t.add_resource(CacheCluster(
"CacheCluster",
..snip..
AZMode=If("HasOneCache", "single-az", "cross-az"),
PreferredAvailabilityZone=If("HasOneCache", Ref(availability_zone), Ref("AWS::NoValue")),
PreferredAvailabilityZones=If("HasOneCache", Ref("AWS::NoValue"), [Ref(availability_zone),Ref(availability_zone2)]),
))
```
=> only validate elasticache az choices if azs is a list

examples/IAM_Roles_and_InstanceProfiles.py, tests/examples_output/IAM_Roles_and_InstanceProfiles.template, troposphere/iam.py
The `Path` property on IAM Roles and Instance Profiles is optional. I added an example that works when deploying to AWS and tweaked the appropriate bools to make this behaviour possible:
```bash
$ aws cloudformation create-stack --stack-name=test-no-path --template-body file://tests/examples_output/IAM_Roles_and_InstanceProfiles.template --capabilities "CAPABILITY_IAM"
{
"StackId": "arn:aws:cloudformation:eu-west-1:MYACCOUNT:stack/test-no-path/GUID"
}
$ aws cloudformation describe-stacks
{
"Stacks": [
{
"StackId": "arn:aws:cloudformation:eu-west-1:MYACCOUNT:stack/test-no-path/GUID", 
"Description": "AWS CloudFormation Sample Template: This template demonstrates the creation of IAM Roles and InstanceProfiles.", 
"Tags": [], 
"CreationTime": "2015-08-17T14:09:59.837Z", 
"Capabilities": [ …
```
=> Path is optional for Role and InstanceProfile

troposphere/__init__.py
Move the cloudformation attribute setting into __setattr__ so the
attributes (like Metadata) can be set after object initialization.
=> Move cloudformation attribute setting to __setattr__

troposphere/utils.py
Since you already know whether the even was seen or not, take advantage of that knowledge to avoid redundant work.
=> tail: only add unseen events

troposphere/ec2.py
LaunchSpecifications should be an array, as in the reference documentation
http://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata.html
=> Correct EC2 SpotFleet LaunchSpecifications

README.rst, examples/CodePipeline.py, tests/examples_output/CodePipeline.template, troposphere/codepipeline.py
As of Dec 3 2015 CloudFormation supports CodePipeline http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
=> Add CodePipeline support

troposphere/codedeploy.py
Previously missing the applicationName parameter to the Application Resource
=> Added applicationName parameter to the application

troposphere/codedeploy.py
DeploymentGroupName property missing from the DeploymentGroup Resource
=> DeploymentGroupName property missing

troposphere/elasticache.py
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-notificationtopicarn
=> ElastiCache: NotificationTopicArn is a string not a list of strings. 

troposphere/cloudtrail.py
Troposphere's CloudTrail is missing one of the parameters listed in the CloudFormation reference <http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-s3bucketname>.
This pull request adds this parameter. 
The code has been tested manually.
=> Adding IsMultiRegionTrail support

troposphere/config.py
Adding missing parameter to Recording Group
=> Adding IncludeGlobalResourceTypes to RecordingGroup

tests/test_validators.py, troposphere/__init__.py, troposphere/iam.py, troposphere/validators.py
This PR adds the option to have custom title validators, as the default one is often to restrictive (AWS allows more characters)
Also there are some new checks for IAM Objects which help you catching errors before you run the CF template.
=> extended title validation

troposphere/logs.py
Hi,
From the doc: 
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html
An IAM role that grants CloudWatch Logs permission to put data into the specified Amazon Kinesis stream. For Lambda and CloudWatch Logs destinations, don't specify this property because CloudWatch Logs gets the necessary permissions from the destination resource.
Required: No
Type: String
Update requires: Replacement
AWS::Logs::SubscriptionFilter RoleArn is mandatory in the library but not on AWS and gives you an error:  destinationArn for vendor lambda cannot be used with roleArn
=> Logs SubscriptionFilter

troposphere/ecs.py
See: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html
=> Fix `ecs.TaskDefinition.Volumes` that was incorrectly flagged as required

examples/CloudFront_S3.py, tests/examples_output/CloudFront_S3.template
Minor typo in variable name.  "S3DNSNAme" -> "S3DNSName"
=> Typo in variable name

troposphere/cloudfront.py
Turns on gzip compression for CloudFront resources.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-defaultcachebehavior.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachebehavior.html
=> Add Compress to CloudFront

examples/CloudFront_S3.py, tests/examples_output/CloudFront_S3.template
According to [AWS CloudFormation docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-origin.html#cfn-cloudfront-origin-s3origin) the parameter S3OriginConfig is mandatory for a S3 backed origin.
=> Added missing S3OriginConfig parameter

troposphere/awslambda.py
Enable Lambda functions to access resources in a Virtual Private Cloud (VPC).
* Announcement: http://aws.amazon.com/about-aws/whats-new/2016/03/aws-cloudformation-updates-amazon-s3-aws-lambda-and-amazon-emr-resources-support/
* Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-vpcconfig
=> Add VpcConfig to AWS::Lambda::Function

troposphere/awslambda.py
Publish a version of a Lambda function.
Announcement: http://aws.amazon.com/about-aws/whats-new/2016/03/aws-cloudformation-updates-amazon-s3-aws-lambda-and-amazon-emr-resources-support/
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html
=> Add Version Resource to awslambda

troposphere/awslambda.py
Create an alias that points to a Lambda function version that you specify.
Announcement: http://aws.amazon.com/about-aws/whats-new/2016/03/aws-cloudformation-updates-amazon-s3-aws-lambda-and-amazon-emr-resources-support/
Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html
=> Add Alias Resource to awslambda

troposphere/autoscaling.py
Fixes #445.
`If` should be a valid expression for MaxCount on an autoscale group(In addition to the already existing `FindInMap` and `Ref` expressions).
=> Ignore If expression during validation of ASG

troposphere/elasticsearch.py
=> DomainName isn't a required parameter

docs/CONTRIBUTE.md
"Explicit is better than implicit."
I got all of the instructions in this documentation commit by following the bread crumbs for the cloudtools/troposphere GitHub repository. It was not hard, but it wasn't as easy as reading a markdown document. My hope is that this commit will make it easier for more people to contribute quality code to this project.
Since there was no `docs` directory, I made an aesthetic choice to put the `CONTRIBUTE.md` file into a sub-directory. I am open to moving it.
=> Create Documentation To Help Contributors

examples/Lambda.py, tests/examples_output/Lambda.template, troposphere/awslambda.py
This is a retry of PR435 after I thoroughly messed up the commit history there. This PR should be much cleaner.
Lambda functions can only have certain amounts of memory in multiples of 64
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-memorysize
This commit allows MEMORY_VALUES to be used against Parameters' AllowedValues attribute, so that the Cloudformation web console form has a drop down selection of memory values in the same way it currently is in the Lambda web console.
I've updated the Lambda example to demonstrate.
I'm aware this could become unwieldy if AWS increase the amounts of memory available to Lambda functions, but if that occurs, this could be reverted or compared with any UI changes in the Lambda web …
=> Provide Valid Lambda Function Memory Values for use in Parameters

troposphere/s3.py
In [Amazon S3 ReplicationConfiguration Rules](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-replicationconfiguration-rules.html) the Destination field use to be a string but it's now an object with [2 documented fields](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-replicationconfiguration-rules-destination.html): Bucket and StorageClass.
=> ReplicationConfigurationRules Destination is now an object

examples/Autoscaling.py, tests/test_examples_template_generator.py, troposphere/__init__.py, troposphere/cloudformation.py, troposphere/emr.py, troposphere/s3.py, troposphere/template_generator.py
This new Template subclass makes it possible to import most Cloudformation templates as JSON and parse them as Troposphere objects. This is different from cfn2py in that it's not trying to write actual python code, but rather instantiate the actual objects without the need to edit it afterwards.
There are probably a few tropo-specific AWSHelperFns that won't be parsed correctly, but the ones included in the tests/examples_output are all supported. I believe an effort should be done to normalize the helper functions into something discoverable with a consistent use - but I have yet to really ponder on that issue.
=> Import JSON Templates

troposphere/config.py
The documentation is unclear but the example (and my testing) shows that this is the correct syntax
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-configrule.html#cfn-config-configrule-source
=> Fix Source object to take a list of SourceDetails

troposphere/ec2.py, troposphere/ecs.py
http://aws.amazon.com/about-aws/whats-new/2016/04/aws-cloudformation-updates-amazon-ec2-amazon-ecs-aws-lambda-and-amazon-gamelift-resource-support/
=> Update to Apr 25, 2016 release

troposphere/s3.py
This adds support for the new 'Transitions' property.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html
AWS deprecated 'Transition' so I added some forward-compatibility support just in case.
=> Implement LifecycleRule Transitions property

troposphere/s3.py
The current implementation will break when attempting to "Ref" the AccessControl to a stack parameter.
=> Fix Bucket AccessControl to allow Ref

.travis.yml, tests/test_validators.py, troposphere/s3.py, troposphere/validators.py
Outline of changes:
- added validation to disallow consecutive periods in bucket name
- added validation to disallow bucket names that look like an IP address
- updated `Bucket` initialization to clarify resource title vs. bucket name, to help avoid more confusion about that in the future
- updated test cases to catch bucket names with capital letters, starting/ending with a period, containing consecutive periods, use of IP addresses
Also, it seems pyflakes 1.2.0 does not work, so I pinned the version to 1.1.0 to help Travis CI pass... not sure if there was a more appropriate solution to that problem.
=> Tune validation logic and test cases for S3 bucket names

scripts/cfn
Working with @markfalk discovered its helpful to have AWS validate the template before stack creation. This change includes these updates while maintaining backwards compatibility:
- Can now use -u or --update to trigger a cfn update action instead of a create action
- Fixes pep8 trailing whitespace
- Fixes pep8 line length to be < 80 chars
=> Validate the template against aws before stack creation

README.rst, examples/EMR_Cluster.py, tests/examples_output/EMR_Cluster.template, troposphere/emr.py
When I tried to create an EMR cluster with EBS volumes, my CloudFormation template yesterday failed.  After creating an AWS support ticket, it appeared the AWS documentation was wrong (EbsConfiguration cannot be specified on Cluster level, but needs to be specified in InstanceGroupConfigProperty).  The documentation has meanwhile been fixed and can be found on http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-emr-cluster-jobflowinstancesconfig-instancegroupconfig.html
The code below reflects this update.
=> EMR: fix EBS configuration

troposphere/emr.py
The documentation lies, here's the error message I just got from CloudFormation:
"CloudFormation currently only supports long-running clusters, set ActionOnFailure to CANCEL_AND_WAIT or CONTINUE"
=> Action on Failure Fix

scripts/cfn
It would be nice if uploading to S3 could be set to a different region than the stack that is being created. This adds a single option to so so with either `-s` or `--s3-region` and maintains backwards compatibility.
=> Allow setting a different region for S3 upload

scripts/cfn
Working with @markfalk discovered its easier to use this script if it has an update option.  This change includes these updates while maintaining backwards compatibility:
- Can now use `-u` or `--update` to trigger a cfn update action instead of a create action
- Fixes pep8 trailing whitespace
- Fixes pep8 line length to be < 80 chars
=> Update not create

troposphere/ec2.py, troposphere/emr.py, troposphere/route53.py
This updates 3 objects that were incorrectly subclassing AWSHelperFn. They are now subclassing AWSProperty as intended. This should be backward compatible.
=> Convert fake AWSHelperFns into AWSProperties

troposphere/ec2.py
* https://aws.amazon.com/about-aws/whats-new/2016/06/aws-cloudformation-adds-support-for-amazon-vpc-flow-logs-amazon-kinesis-firehose-streams-and-other-updates/
* http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-flowlog.html
=> Add support for VPC Flow Logs

tests/test_userdata.py, troposphere/helpers/userdata.py
Rewritten the helper to be more flexible, what kind of delimiter you want to have. The default is now "", which reflects the most used use-case. It's also addresses the issue #465.
=> Re-written userdata from_file helper

examples/Autoscaling.py, tests/examples_output/Autoscaling.template, troposphere/policies.py
- fixes cloudtools/troposphere#511
=> add `AutoScalingReplacingUpdate` to `UpdatePolicy`

tests/test_rds.py, troposphere/rds.py
When creating a read replica using CloudFormation, the read replica will always be created in the default VPC unless the **DBSubnetGroupName** is stated. 
Prior to this PR, **DBSubnetGroupName** is not allowed to be stated when **SourceDBInstanceIdentifier** is stated. 
[AWS documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html) also does not state the **DBSubnetGroupName** cannot be stated when **SourceDBInstanceIdentifier** is. 
A point to note when creating replica is when a read replica is already created in the region, the next read replica will always be created in the same VPC as the first read replica. This has been verified by AWS Support and also this [StackOverflow …
=> Removed validation for DBSubnetGroupName when creating a read replica

examples/EMR_Cluster.py, tests/examples_output/EMR_Cluster.template, troposphere/emr.py
The current master branch contains a too strict EMR configurations validator method: this validator forces configuration values to be strings.  CloudFormation also allows helper functions (which allow you to use for instance a parameter value as configuration value instead of a direct string value).
This branch contains an updated validator method and updated EMR cluster example using an indirect configuration value.
I also updated the EMR example with a parameter dependent choice between spot instances or on-demand instances (using a 'condition').
The EMR example is successfully created in my AWS region eu-west-1.
=> Emr configurations values: also allow AWS helper functions

troposphere/ec2.py
According to
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-ssmassociations-associationparameters.html,
the SsmAssociations AssociationParameters Value is a list of strings,
not a string. This was causing instance creation failure on templates
attempting to use SsmAssociations.
=> Fix AssociationParameters Value type to list of strings

examples/ApiGateway.py, tests/examples_output/ApiGateway.template
DependsOn is required if the RestApi and Method are created in the same template as explained here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html#aws-resource-apigateway-deployment-examples
=> Add DependsOn to Deployment and remove Enabled from StageKey

troposphere/iam.py
Greetings,
Thank you for this excellent software. Per the following documentation:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html
'Status' is not a required property of IAM::AccessKey. I do not know what examples the OP was referring to, but IAM::AccessKey does actually default to 'Active'
Thanks!
Niko
=> do not require Status as a property in iam.AccessKey

troposphere/iam.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-group.html#cfn-iam-group-groupname
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-rolename
=> Add Name attributes for IAM groups and roles

troposphere/template_generator.py
template_generator.py was incorrectly invoking pkgutil.walk_packages,
passing in the filepath directly rather than as a list of paths. By
coincidence, this resulted in the current directory being processed
instead, which allowed the tests to accidentally pass.
Fixes #532
=> Fix TemplateGenerator import logic.

tests/test_template.py, troposphere/__init__.py
Similar to the resource classes, this allows Description and Metadata to be set on construction.
Currently you have to do:
```python
template = Template()
template.add_description('Blah blah blah ...')
```
This PR makes it more consistent with other resources and allows:
```python
template = Template(Description='Blah blah blah ...')
```
=> Extend Template constructor.

troposphere/cloudfront.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
=> CloudFront updates (Aug 9, 2016)

troposphere/iam.py, troposphere/validators.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-user.html#cfn-iam-user-username
=> Support "UserName" property for AWS::IAM::User

tests/test_awslambda.py, troposphere/awslambda.py
This reworks the check_zip_file function (https://github.com/cloudtools/troposphere/pull/537 and https://github.com/cloudtools/troposphere/commit/1f69f01155105117eb2e543d2a96569e2bae3a3c) to always try to get a minimum length, even if not all parts are strings.
My original plan was to only replace `return` on line 56 with `continue`, but when I started writing it, I saw that I could also  use list comprehension instead of a loop (and make the variable name use snake_case).
=> Improve check_zip_file to calculate a minimum length

troposphere/apigateway.py
"Body" is a dict now: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
=> Change param type for resource: RestAPI

tests/test_dict.py, tests/test_ecs.py, troposphere/ecs.py
Even though the Cloudformation Documentation has not been updated to mention the TaskRoleArn property for TaskDefinitions, it is supported and successfully provisions task definitions with IAM Roles, as described in the API documentation:
http://docs.aws.amazon.com/cli/latest/reference/ecs/register-task-definition.html
=> Add support for IAM Roles in ECS Task Definitions

tests/test_ecs.py, troposphere/ecs.py
This is now supported in CloudFormation. From http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinitions-portmappings.html
=> Added support for protocol in container definition's PortMapping property.

troposphere/elasticsearch.py
Similar to #556, there's now cloudformation support for specifying the desired ES version, but it's not added to their official docs. I stumbled upon [this StackOverflow thread](http://stackoverflow.com/questions/38796017/aws-elasticsearch-domain-cloudformation-template) when I was trying to find out whether it's supported. I've verified that the param is indeed supported.
=> Add support for ElasticsearchVersion in Elasticsearch Domain

examples/CertificateManagerSample.py, tests/examples_output/CertificateManagerSample.template, troposphere/certificatemanager.py
Certificate Manager certificates support tagging: see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html
=> add support for Tags to Certificate Manager Certificates

troposphere/logs.py
Docs [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html)
=> Add support for LogGroupName in Logs::LogGroup

tests/test_asg.py, troposphere/autoscaling.py
If you tried to use an AWSHelperFn object in an UpdatePolicy for an ASG,
you would run into issues because of the extra validation.  This
disables the extra validation whenever the UpdatePolicy is an
AWSHelperFn, which is in line with the way troposphere usually handles
these things.
=> Allow HelperFn in UpdatePolicy for ASG

tests/test_dict.py, troposphere/__init__.py
This validates properties & sub-properties when using from_dict.
=> Provide better type checking for values in from_dict

tests/test_dict.py, troposphere/__init__.py
=> Fixes the case where you have a list of non BaseAWSObjects

troposphere/iam.py
The title specified in troposphere is not the actual physical resource name and should be validated as such.
The original pull request was https://github.com/cloudtools/troposphere/pull/429, cc @phobologic.
=> Remove `title` validation. Fixes #428 (attempt 2)

examples/EFS.py, tests/examples_output/EFS.template
After deploying EFS myself and seeing https://github.com/cloudtools/troposphere/issues/580 decided to give back and add an EFS example.
I purposely made it a a reasonably interesting example with security groups, IAM artifacts etc since that's probably a more realistic real-world example. The examples have helped me tremendously in the past but you often have to pull info from several different ones to get a full picture.
=> Add EFS example

troposphere/rds.py
This is a Backward compatibility change proposal.
I got old templates generated with troposphere that needs as db engine parameter 'mysql' in order to avoid the replacement of the RDS during a stack update.
=> add support to old mysql db engine

scripts/cfn2py
Hi! I was porting some JSON template files to Troposphere using cfn2py, and realised that the conditions (both their declaration and their use in resources) were being ignored by the script.
I've added support for conditions, and it has worked well so far.
=> Add support for conditions in cfn2py script

examples/CloudFront_S3.py, tests/examples_output/CloudFront_S3.template, troposphere/cloudfront.py
CloudFront now supports HTTP/2, this allow that property to be set in CloudFormation via Troposphere.
Support landed in CF to support this property on the 3rd November 2016, see: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/
http://docs.aws.amazon.com/AmazonCloudFront/latest/APIReference/CreateDistribution.html
=> Add HttpVersion prop to DistributionConfig (CloudFront HTTP/2 Support)

troposphere/cloudfront.py
=> Added missing QueryStringCacheKeys property to CloudFront ForwardedValues

tests/test_validators.py, troposphere/elasticloadbalancing.py, troposphere/elasticloadbalancingv2.py, troposphere/validators.py
The LoadBalancerName has some constraints that we can validate for ahead of time:
> This name must be unique within your set of load balancers for the region, must have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, and cannot begin or end with a hyphen.
From: http://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_CreateLoadBalancer.html
My current implementation of the regex doesn't quite work.  A one character name ought to work but I have created a regex that will fail on names of one character.  I could use some help on it.
=> Add a validator for ELB names

troposphere/awslambda.py
AWS Just added Lambda environment variables
https://aws.amazon.com/about-aws/whats-new/2016/11/aws-cloudformation-supports-aws-serverless-application-model-aws-lambda-environment-variables-and-new-cli-commands/
Here is how it can be used in troposphere
```
Function(
"FunctionWithEnvironment",
Description="Lambda Environment feature is awesome",
Code=Code(
S3Bucket="s3_bucket_name",
S3Key="key/file.zip",
),
Environment={
"Variables": {"ENV_NAME": "env_value"}
},
Handler="handler.index",
Role=GetAtt(lambda_role, "Arn"),
Runtime="python2.7",
Timeout=10
)
```
in lambda python code:
```
import os
print("ENV_NAME={}".format(os.environ.get('ENV_NAME')))
```
=> Allow environment variable feature 

troposphere/awslambda.py
@markpeek - The `Environment` variable for a lambda `Function` is not just a dict, it has a specific format as defined here:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-environment.html
Discovered this after much head bashing.  I think this will improve usage of the code for others.
=> Create new property Environment for aws lambda Function

troposphere/sns.py
Added an SNS subscription object, to allow us to create SNS
subscriptions as seperate objects, rather than just as properties
of an SNS topic.
=> Added SNS::Subscription object

examples/CloudWatchEventsSample.py, tests/examples_output/CloudWatchEventsSample.template
In the example it was missing t.add_resource and therefore wasn't outputting the rule in the json.
=> Fixed missing add_resource in example Cloudwatch rule

troposphere/template_generator.py
The use of dictionary comprehension in #468 caused support for Python
2.6 to be dropped. This change converts these comprehensions to use
simple iteration.
See b8a6dae for a prior example of dictionary comprehensions breaking support. This fix was modeled after that commit. As per that commit the test suite does not run in Python 2.6, however I have tested that `pycodestyle .` and `pyflakes .` both pass when running using python2.6.6 and the unit tests pass when using 2.7.11.
Potentially Travis could be configured to run `pycodestyle` and `pyflakes` under python 2.6 to help with the "best effort" support so even if the unit tests can't run it'll help spot compilation errors but that's a discussion for another day.
(Oh I'm using python2.6 rather than upgrading because I'm still stuck on …
=> Add back support for Python 2.6

troposphere/rds.py
Currently troposphere doesn't support oracle-se2 as an engine choice. Added support & tested, working as expected.
=> Adding RDS engine support for oracle-se2

tests/test_basic.py, troposphere/__init__.py
This implements the Fn::Split function announced here:
https://aws.amazon.com/about-aws/whats-new/2017/01/aws-cloudformation-introduces-support-for-listing-imports-split-function-and-resource-coverage-updates/
I guess there should be a test case, but there isn't one for its partner Fn::Join, so perhaps I should create one for both?
=> Add Fn::Split function

troposphere/rds.py
This allows you to use a Ref("AWS::NoValue") for example in both Iops
and StorageType (which would result in standard storage, no iops).
=> Allow use of AWSHelperFn for IOPS

tests/test_basic.py, tests/test_codecommit.py, tests/test_ec2.py, tests/test_ecs.py, tests/test_logs.py, tests/test_policies.py, tests/test_rds.py, tests/test_tags.py, tests/test_userdata.py, troposphere/__init__.py, troposphere/autoscaling.py, troposphere/cloudformation.py, troposphere/ec2.py
This removes the JSONrepr methods and replaces with to_dict() which
handle creating dicts for each of the individual objects. The to_json()
method then just calls to_dict() on self and marshals the resulting
dictionary. Adding to_dict() allows for output into other formats such
as YAML without needing to output JSON and then reload it back just to
output in another format.
This can be considered a breaking change if others are calling JSONrepr. If needed I can re-add the JSONrepr functionality back to make this backwards compatible.
=> Added to_dict() method to troposphere.Template

tests/test_validators.py, troposphere/elasticloadbalancingv2.py, troposphere/validators.py
For the TargetGroup in ElasticLoadBalancerV2 you can set the HealthCheckPort to the string `traffic-port`, which is the default if not set.  This is documented here:
http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html
I've added a new validator and tests for this.
=> Allow valid value for TargetGroup HealthCheckPort

troposphere/ssm.py
The SSM Target Property only support "Values" not "Value"
Source:
http://docs.aws.amazon.com/ssm/latest/APIReference/API_Target.html
=> SSM Target fix Values instead of Value

tests/test_apigateway.py, troposphere/apigateway.py
Allow both a string and dict for the ApiGateway::Model Schema.
The string form is checked for a valid json string and the dict
form is converted into a json string.
=> Do json validation on ApiGateway::Model Schema (Fix #679)

troposphere/ec2.py
Adding PeerOwnerId & PeerRoleArn
```
{
"Type" : "AWS::EC2::VPCPeeringConnection",
"Properties" : {
"PeerVpcId" : String,
"Tags" : [ Resource Tag, ... ],
"VpcId" : String,
"PeerOwnerId" : String,
"PeerRoleArn" :  String
}
}
```
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcpeeringconnection.html
=> VPCPeeringConnection: add PeerOwnerId & PeerRoleArn

troposphere/iam.py
Add InstanceProfileName to InstanceProfile
```
{
"Type": "AWS::IAM::InstanceProfile",
"Properties": {
"Path": String,
"Roles": [ IAM Roles ],
"InstanceProfileName": String
}
}
```
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html
=> IAM: Add InstanceProfileName to InstanceProfile

troposphere/redshift.py, troposphere/route53.py
**AWS::Route53::HealthCheck**
There are seven new resource subproperty types for the Amazon Route 53 HealthCheckConfig HealthCheckConfig property: AlarmIdentifier, ChildHealthChecks, EnableSNI, HealthThreshold, InsufficientDataHealthStatus, Inverted, and MeasureLatency.
```
{
"AlarmIdentifier" : AlarmIdentifier,
"ChildHealthChecks" : String,
"EnableSNI" : Boolean,
"FailureThreshold" : Integer,
"FullyQualifiedDomainName" : String,
"HealthThreshold" : Integer,
"InsufficientDataHealthStatus" : String,
"Inverted" : Boolean,
"IPAddress" : String,
"MeasureLatency" : Boolean,
"Port" : Integer,
"RequestInterval" : Integer,
"ResourcePath" : String,
"SearchString" : String,
"Type" : String
}
```
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-healthcheck-healthch …
=> Add new subproperties to route53 and redshift

tests/test_tags.py, troposphere/__init__.py, troposphere/template_generator.py
The implementation of Tags has limitations due to the use of
kwargs for initialization. This change adds the ability to
initialize Tags using a dict.
@kaarolch @brandonshough @tomdeblende @tamas7 does this match the use cases for the issues filed on this behavior?
=> Allow a dict to be passed in to initalize Tags

examples/Autoscaling.py
The example imports the `LaunchConfiguration` class object, but then rebinds the `LaunchConfiguration` name to an instance of the class, preventing any further use of the `LaunchConfiguration` class object. This patch binds the instance object to a new variable name, keeping `LaunchConfiguration` bound to the original class object.
=> Update autoscaling example to remove rebinding

troposphere/awslambda.py
The [April 28, 2017 release](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) included support for `Tags` on the `AWS::Lambda::Function` resource.
=> Add new AWS::Lambda::Function Tags support

.gitignore, tests/test_ecs.py, troposphere/ecs.py, troposphere/validators.py
Added placement strategies and placement constraints for the ecs services. 
We could also add this to task definitions. 
Let us know if you'd like to do that and we can add it
=> Added ECS PlacementConstraints, PlacementStrategy, and ServiceName

troposphere/ec2.py
Add IPv6 address related properties to ec2.NetworkInterface
Reference: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-network-interface.html
Made Ipv6Addresses use the property 'Ipv6Address' instead of 'Ipv6Addresses'.
Reference: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-networkinterface-ipv6addresses.html
Add GroupName property to ec2.SecurityGroup
Reference: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
=> Add missing properties to various objects in ec2.py

troposphere/constants.py, troposphere/logs.py, troposphere/validators.py
When definining number of retention days for log group, it must be value from strictly defined list; if other value will be provided, CloudFormation will raise an error during stack creation
=> logs.LogGroup#RetentionInDays is strictly defined list

troposphere/ec2.py
Discovered a missing ipv6 parameter to the ec2.SecurityGroupRule object.
See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html
=> Add missing CidrIpv6 property to ec2.SecurityGroupRule.

troposphere/__init__.py
This is so common I figured it might be worth just attaching the
behavior to the base AWSObject.  Would mean a couple less imports, and
it feels more pythonic.
=> Added .Ref & .GetAtt helper methods

troposphere/emr.py
The EMR InstanceGroupConfig is missing JobFlowId which is a required parameter and specifies the EMR cluster in which the instance group should be created. This PR adds that attribute and marks it as required.
=> Add required attribute, JobFlowId, to EMR::InstanceGroupConfig

examples/WAF_Regional_Common_Attacks_Sample.py, tests/examples_output/WAF_Regional_Common_Attacks_Sample.template, troposphere/wafregional.py
Add WAFRegional (WAF for ElasticLoadbalancingv2) support introduced in https://aws.amazon.com/about-aws/whats-new/2017/05/cloudformation-support-for-aws-waf-on-alb/
=> Add WAFRegional support

examples/ElastiCacheRedis.py, tests/examples_output/ElastiCacheRedis.template
Thought this would be useful as the comments suggest that it should be done with awacs.
=> fix for ElastiCacheRedis.py example to use awacs

tests/test_template.py, troposphere/__init__.py
Raises ValueError when CloudFormation template limits are reached for Outputs or Mappings.
Test cases included and passing.
Thanks!
=> Raise ValueError for Outputs and Mappings - Fix Issue #732

troposphere/cloudwatch.py
These new Cloudwatch alarms properties are documented here : http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/AlarmThatSendsEmail.html#alarms-and-missing-data
CloudFormation API doc is not up to date right now though.
=> feat(Cloudwatch): add support for latest Cloudwatch alarms properties

examples/ApiGateway.py, tests/examples_output/ApiGateway.template
This pull request is simply to include Usage Plans into the example provided.
=> Added UsagePlans to API Gateway example

tests/test_emr.py, troposphere/emr.py, troposphere/validators.py
This is my attempt to help button up #736. This should incorporate @alexwen's code with the addition of a `validate` method to perform the more complex `AdjustmentType` and `ScalingAdjustment` validations that @markpeek requested in the original PR. 
This PR also introduces an `ignore` method in validators.py that is implemented to "bypass" (for lack of a better term) so the simple property validation is "skipped' and the new `validate` method in `emr.py` is used.
The reasoning for the `ignore` method is that the `ScalingAdjustment` property in `SimpleScalingPolicyConfiguration` will actually take different types depending on the value of  `AdjustmentType`. 
As a result, we need to skip the initial checking in favor of the more complex validation.
**Old**:
```class …
```
=> EMR AutoScaling Complex Validation and Introduction of an ignore validator type

tests/test_basic.py, troposphere/__init__.py
Now you can pass troposphere resources directly into the DependsOn
attribute, and troposphere will figure out the title of that resource
for you automatically.
=> Make handling of DependsOn more pythonic

examples/EFS.py, tests/examples_output/EFS.template
Closes low hanging fruit #709
As part of this change, I removed the `title` usage in favor of the positional argument for naming a resource. Using the positional seems to be the defacto standard looking at other examples and code within Troposphere.
=> EFS DependsOn Ref to String fix

.editorconfig, .gitignore, Makefile, examples/Serverless_Api_Backend.py, examples/Serverless_S3_Processor.py, tests/examples_output/Serverless_Api_Backend.template, tests/examples_output/Serverless_S3_Processor.template, tests/test_serverless.py, tests/test_template.py, troposphere/__init__.py, troposphere/serverless.py, troposphere/template_generator.py
@dogonthehorizon did almost all the heavy lifting for this one. I fixed the bug mentioned in the previous PR #671.
I did this by adding a `cls` argument to the `TemplateGenerator._convert_definition` method. If the `cls` argument is provided it will attempt to create an instance of the provided class. If it is not provided then no classes will be made.
Then the only place where this `cls` argument is provided is in the `TemplateGenerator.__init__` method when adding resources.
All the tests pass but I am suspicious of my fix, it seemed too simple for such and annoying bug.
=> Completed AWS SAM support

troposphere/codebuild.py
CodeBuild now allows you to run your build containers in `privileged mode`. They rolled this feature out pretty silently it seems because I can't find any announcements or product updates about it. They also haven't added it to the CloudFormation documentation yet either. I can only find a reference to it in this document on creating a project:
http://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli
I can confirm that CloudFormation supports this option because I have created a template for a CodeBuild project and added this in manually. Worked as expected.
=> Add PrivilegedMode option to CodeBuild Environments

troposphere/codebuild.py
The Source property in the `AWS::CodeBuild::Project` type can optionally take an `Auth` parameter when the Source Type is 'GITHUB'. This tells CodeBuild to use the OAUTH method of authenticating to private repositories.
There is no direct documentation of this, but they describe it's use in this article:
http://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli
You can only specify 'Auth' in the Source object when the Type is GITHUB. If you specify Auth in the Source object, the Auth Type can only be 'OAUTH'
=> Add 'Auth' property to CodeBuild Source

troposphere/sqs.py
Add a validate() method in sqs.py that checks that FIFO queues
(*) have a QueueName parameter and (*) QueueName ends with '.fifo'
as required by AWS:
http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html
=> Check that FIFO Queues end with .fifo

troposphere/ecs.py
Ulimit's HardLimit and SoftLimit validator needs to be integer and not positive_integer.
http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_limits
For example memlock can be -1:-1 as required by:
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docker.html#_notes_for_production_use_and_defaults
=> Ulimit's HardLimit and SoftLimit validator change

tests/test_cloudwatch.py, troposphere/cloudwatch.py
The dict should be converted into a json encoded string
This logic is taken from the [ApiGateway Model](https://github.com/cloudtools/troposphere/blob/d583dfb78b8d207b26070ae1894f7e36a1b39017/troposphere/apigateway.py#L188), whose Schema property also returns a json encoded string.
An example of using this, where both dashboard resources produce the same Cloudformation:
```python
from troposphere import Template
from troposphere.cloudwatch import Dashboard
t = Template()
t.add_resource(Dashboard(
"dashboard",
DashboardBody={"c": "d"}
))
t.add_resource(Dashboard(
"dashboardstring",
DashboardBody='{"c": "d"}'
))
print(t.to_json())
```
=> Allow passing in a dict into DashboardBody

tests/test_parameters.py, troposphere/__init__.py
I'm getting a validation error with valid parameter:
Parameter default type mismatch: expecting type String got <class 'troposphere.Join'> with value <troposphere.Join object at 0x7f786b807d10>
due to using a Join as the default.
Changed validation check to allow Join type.
=> Accept Join type as parameter default value as it returns a string

.travis.yml, troposphere/efs.py
Announcement [here](https://aws.amazon.com/blogs/aws/new-encryption-at-rest-for-amazon-elastic-file-system-efs/)
Cfn docs [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html)
I also took the opportunity to fix the busted build by expanding the `2to3` usage to `scripts/cfn2py`. Let me know if you'd rather me pull this into a separate PR.
=> Add support for EFS encryption

MANIFEST.in, setup.py
I noticed that the MANIFEST.in file was referencing a Markdown README instead of a reStructuredText README.
Also, the PyPI website for this library has practically no information. I think it would be beneficial to copy the README.rst file over to the PyPI page as well.
=> Update PyPI Information

.travis.yml, tests/test_basic.py, troposphere/__init__.py
Add a parameter to allow for the override of object validation which has come up due to complex interaction of properties within an object. While longer term a full expression parser may help with the validation logic, there are still some instances that cannot be determined except at runtime with this override allowing for the template author to make the determination on whether to override the validation logic. This is a fix for #778.
=> Override object validation

tests/test_apigateway.py, troposphere/apigateway.py
Adds support for [AWS::ApiGateway::GatewayResponse](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-gatewayresponse.html). 
Unfortunately, there seems to currently be a bug in CloudFormation which blocks creating GatewayResponses (https://forums.aws.amazon.com/thread.jspa?messageID=801223). However, I think it's still worth adding support for creating these objects according to the spec in the docs.
It's my first PR and I'm not sure about the conventions in the project so please let me know if anything needs to be changed accordingly.
=> Add AWS::ApiGateway::GatewayResponse

troposphere/rds.py
Aurora PostgreSQL is currently in preview and is accessible via CloudFormation. This requires aurora-postgresql to be a valid DB engine selection.
=> Add support for aurora-postgresql as a valid DB engine

troposphere/ec2.py
Added the `CidrBlock` property to VPCCidrBlock to support [adding a second CIDR block to a VPC](https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-virtual-private-cloud-vpc-now-allows-customers-to-expand-their-existing-vpcs/). Addresses Issue #795.
=> VPC expansion support

troposphere/batch.py
Support AWS batch per issue #781. This is somewhat of a draft of the whole thing to make sure the overall structure looks sane before I go up and CloudFormation all the things. Note that for the `JobQueue` resource's state property I diverged from the CF documentation and used the REST API documentation for `CreateJobQueue` which states that `ENABLED` or `DISABLED` are valid values. 
The following resources are added:
* [AWS::Batch::ComputeEnvironment](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-computeenvironment.html)
* [AWS::Batch::JobDefinition](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html)
* [AWS::Batch::JobQueue](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch- …
=> AWS Batch Support

troposphere/cognito.py
SchemaAttribute documentation mentions that the "Required" field is a boolean, similar to the "Mutable" field. Wasn't sure if it was just an oversight but to avoid confusion I thought it should also accept plain boolean values.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-schemaattribute.html
=> Change Cognito UserPool SchemaAttribute "Required" value to boolean from basestring

troposphere/ec2.py
Turns out the AWS documentation was incorrect, and that "P" was supposed to be upper case (despite the fact the underlying API does not do this).
=> Updating case of 'AssignIPv6AddressOnCreation'

examples/EFS.py, tests/examples_output/EFS.template
Because the `SecurityGroupRule` isn't added into the template, `Ref` doesn't work here. The `SecurityGroup` constructor should refer to the `SecurityGroupRule` object directly.
=> EFS example: SecurityGroupRule can't be referred to as a Ref

troposphere/cloudtrail.py
Enables data source events for CloudTrail. Please have a look here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudtrail-trail-eventselector.html.
=> Added CloudTrail EventSelectors

examples/AutoscalingHTTPRequests.py, tests/examples_output/AutoscalingHTTPRequests.template
@BardiaAfshin requested someone write an example that does autoscaling based on the number of requests an ELB gets. This is an example I wrote. Most of it was copied from the original autoscaling example but with scaling added that uses the Request Count metric from the ELB's cloudwatch metrics.
=> adding autoscaling example for http requests that closes #630

troposphere/ec2.py
Add Tags support to the `AWS::EC2::NatGateway` class
Closes #826
=> Add Tags to NATGateway

troposphere/firehose.py
The `KinesisStreamSourceConfiguration` is missing from `firehose.py`. Official docs are [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html).
One thing to note is `DeliveryStreamType` is missing from the docs but is present in the examples - it's required to make the source configuration work.
=> Adding kinesis stream source to firehose

examples/S3_Bucket_With_AccelerateConfiguration.py, tests/examples_output/S3_Bucket_With_AccelerateConfiguration.template, tests/test_basic.py, troposphere/s3.py, troposphere/validators.py
This addresses #832
Example output matches the spec at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-accelerateconfiguration.html
=> Add S3 Transfer Acceleration to AWS::S3::Bucket

troposphere/elasticbeanstalk.py
Add the `ResourceLifecycleConfig` property to the `AWS::ElasticBeanstalk::Application` Class.
Closes #827
=> Add ResourceLifecycleConfig to ElasticBeanstalk

troposphere/autoscaling.py
Per the AWS docs, the `AdjustmentType` property is only supported for simple and step scaling policies and is no longer a required property of `AWS::AutoScaling::ScalingPolicy`. This change will allow for creating target tracking scaling policies without having to specify `AdjustmentType`, which is not used.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-adjustmenttype
http://docs.aws.amazon.com/AutoScaling/latest/APIReference/API_PutScalingPolicy.html#API_PutScalingPolicy_RequestParameters
=> Make AdjustmentType an optional property of ScalingPolicy

tests/test_serverless.py, troposphere/serverless.py
SAM(Serverless) is missing some of the function properties, add following properties to the template:
* Tags
* Tracing
* KmsKeyArn
* DeadLetterQueue
* CodeUri, This has been covered in another PR [#852](https://github.com/cloudtools/troposphere/pull/852)
=> Add Tags, Tracing, KmsKeyArn, DLQ to serverless(SAM)

troposphere/ec2.py
I've been trying to set NoDevice but am getting errors. Troposphere requires dict but I get a CF error "Value of property NoDevice must be of type String" when I use dict, even if a create an empty one.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/block-device-mapping-concepts.html
It looks like it always wants "" so I assume changing the type to basestring will enable this to work.
(Sorry I wasn't sure if I should have raised an issue first but just dived in :) )
=> EC2 NoDevice should be type boolean not dict

troposphere/batch.py
[Cloudformation documentation for AWS::Batch::JobQueue](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobqueue.html) specifies that this parameter is not required.
=> Make AWS::Batch::JobQueue::JobQueueName optional

troposphere/analytics.py
Both InputSchema[0] and ReferenceSchema[1] should be a list of RecordColumn
instead of a RecordColumns
[0]: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalytics-application-inputschema.html
[1]: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalytics-applicationreferencedatasource-referenceschema.html
=> Fixes RecordColumns cardinality for InputSchema and ReferenceSchema

troposphere/analytics.py
The Output[0] property should be an object instead of a list of objects.
The official documentation is not clear about this but creating an
ApplicationOutput with a list of Output objects will fail with the message:
Property validation failure: [Value of property {/Output} does not match type {Object}]
while creating an ApplicationOutput with an Ouput object will succeed.
[0]: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalytics-applicationoutput.html
=> Fixes ApplicationOutput/Output cardinality

examples/EC2_Remove_Ephemeral_Drive.py, tests/examples_output/EC2_Remove_Ephemeral_Drive.template, troposphere/ec2.py
Reverts EC2->BlockDeviceMapping->NoDevice property to type dict, allowing for a value of `{}` as shown in the [documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-mapping.html#cfn-ec2-blockdev-mapping-nodevice) under the `Unmapping an AMI-defined Device` example.
Also adds an example template of unmapping ephemeral devices on an EC2 instance.
Fixes #865
=> Set EC2 BlockDeviceMapping NoDevice property to type dict

troposphere/codecommit.py
Updates `Trigger` validation to also accept `AWSHelperFn` objects or a list of `AWSHelperFn` objects.
Fixes #868
=> Allow AWSHelperFn for CodeCommit Trigger Event(s)

troposphere/ssm.py
Hello,
The template created by this class fails on AWS deployment:
```
Property validation failure: [Encountered unsupported properties in {/ApprovalRules/PatchRules/0/PatchFilterGroup}: [Values, Key]]
```
The expected property from the AWS side is the group property. This update fixes and creates a valid CloudFormation template.
=> Fixes incorrect class definition.

troposphere/ec2.py
As spotted by @justjulian, without any warning AWS has changed the casing of `AssignIpv6AddressOnCreation` on AWS::EC2::Subnet. This effectively reverts #810.
=> Changing the casing of 'AssignIpv6AddressOnCreation' again

troposphere/cloudfront.py
Allows Tags to be added to cloudfront distribution as outlined here:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution.html#cfn-cloudfront-distribution-tags
=> Adds Tags to Cloudfront Distribution

tests/test_parameters.py, troposphere/__init__.py
Parameters also allow being used in a reference. Right now it's only possible by using the string reference. Being able to use the `ref()` function makes it a bit more convenient.
=> Allow ref on Parameter

troposphere/kms.py
AWS::KMS::Key doesn't currently support the Tags property. This change add this functionality. 
Fixes issue: #889
=> Add support for tags in AWS::KMS::Key.

troposphere/ec2.py
#885 added `Description` for `SecurityGroupRule` but not for `SecurityGroupIngress` nor `SecurityGroupEgress`.
=> Add Description property for security group ingress and egress

README.rst
This pull request will also inform users that we can create the AWS CloudFormation template in YAML also,
In order to do this we have to use print(template.to_yaml()) instead of print(template.to_json()).
Hence we can create YAML template from the troposphere.
=> Updated for YAML template

examples/ECSFargate.py, tests/examples_output/ECSFargate.template, tests/test_ecs.py, troposphere/ecs.py
This updates the ECS Service type to support the new properties for enabling VPC networking and Fargate support.
=> Add Fargate support to ECS types

examples/Batch.py, tests/examples_output/Batch.template, troposphere/batch.py
AWS Batch seems to use a different Tag format. Instead of the usual
```
{
'Key': 'TagKey',
'Value': 'TagValue'
}
```
AWS Batch expects a regular map `{'TagKey': 'TagValue'}`.
This commit also adds an example template for AWS Batch.
=> Change AWS::Batch::ComputeResources.Tags type to dict

troposphere/ssm.py
fix the validator, otherwise it raises the `error isinstance() arg 2 must be a type or tuple of types`
```
File ".../templates/common/ssm/common_ssm_v1.py", line 165, in main
NotificationType=utils.parse_arg(notification_config, name="type")
File ".../lib/python3.6/site-packages/troposphere/__init__.py", line 341, in __init__
super(AWSProperty, self).__init__(title, **kwargs)
File ".../lib/python3.6/site-packages/troposphere/__init__.py", line 124, in __init__
self.__setattr__(k, v)
File ".../lib/python3.6/site-packages/troposphere/__init__.py", line 189, in __setattr__
if not isinstance(v, tuple(expected_type)) \
TypeError: isinstance() arg 2 must be a type or tuple of types
```
=> SSM Notification config fix

troposphere/elasticloadbalancingv2.py
This change removes the validation step from the LoadBalancer class to allow for conditionally setting one of these properties, while setting the other to `AWS_NO_VALUE`
Fixes cloudtools/troposphere#933
=> remove elasticloadbalancingv2 LoadBalancer Validation

tests/test_serverless.py, troposphere/serverless.py
Hi there -
Thanks for troposphere!
I was trying to use it to build a Serverless Application Model (SAM) definition and discovered that the `AutoPublishAlias` attribute was not supported.  
Based on the [SAM spec](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md), `AutoPublishAlias` should be allowed as an optional attribute.
I've added support for it and a test.  LMK if all looks right as this is my first PR here.
Best,
-Donnie
=> Added support for AutoPublishAlias to AWS::Serverless::Function

tests/test_guardduty.py, troposphere/guardduty.py
Unit tests confirm construction of these objects and ensure that the
`Type` field is set properly in the output dict to prevent regressions.
See: https://github.com/cloudtools/troposphere/issues/944
=> Add resource_type value and unit tests for guardduty `AWSObject`s

troposphere/constants.py
Amazon added the new EC2 M5 instance type last month. This simply adds the new types to the list of Troposphere constants. See https://aws.amazon.com/ec2/instance-types/m5/#Product_Details for details.
=> Add constants for EC2 M5 instance types

troposphere/__init__.py
currently, troposphere to_yaml function will by default use the short form.  This causes tag issue with yaml parsers.  cfn_flip already has the option to turn on the long form, so this should be passed through so that it can be used in troposphere.
=> Add long form parameter to to_yaml

troposphere/rds.py
DBInstance::validate() fails when using Python3 if AllocatedStorage is set to the string representation of an integer,  even through positive_integer() accepts the string representation of a positive integer.
DBInstance::validate() attempts to compare the value of AllocatedStorage with integers, leading to an implicit conversion that throws a TypeError with Python3.
Explicitly converting allocated_storage when comparing it to integers solves the issue without impacting the same use case when executed with python2.
Test results:
test_response_type (tests.test_apigateway.TestGatewayResponse) ... <class 'troposphere.apigateway.GatewayResponse'>: GatewayResponse.ResponseType function validator 'validate_gateway_response_type' threw exception:
ok
test_schema (tests.test_apigateway.TestModel) …
=> Explicitly convert allocated_storage to integer before using it in comparisons

tests/test_cloudformation.py, troposphere/cloudformation.py, troposphere/validators.py
This [reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-waitcondition.html) states ```If you use a CreationPolicy with a wait condition, do not specify any of the wait condition's properties.```. This PR enforces this and allows for CreationPolicy to override the "required" fields for WaitCondition. Fixes #986
=> Allow CreationPolicy override of props on WaitCondition

troposphere/apigateway.py
- Remove CertificateArn requirement from ApiGateway:DomainName to deploy
ApiGateway REGION deployment w/ssl
=> ApiGateway::DomainName CertificateArn fix

troposphere/batch.py
According to cloudformation document https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-jobdefinitionname
=> "JobDefinitionName" property in JobDefinition class is not required

troposphere/ssm.py
SSM Documents now support tags (#999)
Tested by adding tag information to some documents I've generated via Troposphere - when I updated the stack with new template - tags were successfully added to the documents.
=> Tags support for SSM documents #999

troposphere/ec2.py
The new support for adding tags to Spot Fleets created in CloudFormation [works a bit differently](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications.html#cfn-ec2-spotfleet-spotfleetlaunchspecification-tagspecifications) than was added in c4ee115e -- the property is TagSpecifications (vs. TagSpecification) and it must be a list.
The SpotFleetTagSpecification property ResourceType [claims it's not required](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata-launchspecifications-tagspecifications.html#cfn-ec2-spotfleet-spotfleettagspecification-resourcetype) but I get "Tag specification resource type must have a value" in CloudFormation …
=> Correct Spot Fleet TagSpecifications

troposphere/appsync.py
Fixes issue https://github.com/cloudtools/troposphere/issues/1039
The expires prop on the appsync ApiKey class needs to be an int otherwise the decimal place causes cloudformation to throw a `Can not deserialize value of type java.lang.Long from String` error.
=> Updated appsync apikey expires to be an int: Fixes #1039

examples/EMR_Cluster.py, tests/examples_output/EMR_Cluster.template
changed to
python emr.py | grep EMR_AutoScaling_DefaultRole
"AutoScalingRole": "EMR_AutoScaling_DefaultRole",
from
python emr.py | grep EMR_AutoScaling_DefaultRole
"Ref": "EMR_AutoScaling_DefaultRole"
=> Fix AutoScalingRole in EMR: Fixes #984

.travis.yml
https://www.python.org/download/releases/3.3.0/
=> Remove python 3.3 support since it's EOL

troposphere/template_generator.py
When using the TemplateGenerator, the following warning message appears:
UserWarning: This module has replaced by troposphere.dynamodb. Please import that module instead, as troposphere.dynamodb2 will be removed soon.
=> Update deprecated modules in TemplateGenerator

troposphere/codebuild.py
Added support for Github Enterprise as a source for Codebuild. Support for 'GitCloneDepth' and 'InsecureSsl' were added in the last release but the source types were not updated.
=> Update Codebuild Sources to include Github Enterprise

.travis.yml, tests/test_basic.py, troposphere/__init__.py
This is largely used by the Pseudo Parameters, so that these three
properties are all the same:
```
from troposphere import NoValue, Ref
s = "AWS::NoValue"
r = Ref(s)
s == r
s == NoValue
r == NoValue
```
This is in preparation for another PR to fix the validators for
`mutually_exlusive` and `exactly_one` - which should both allow
multiple values provided the values are set to `AWS::NoValue`
=> Allow Ref's to test equality against their data

setup.py
cfn-flip 1.0.2 fixes the issue where zero-prefixed strings are not quoted which confuses the CloudFormation service
=> Update to cfn-flip 1.0.2

tests/test_basic.py, troposphere/__init__.py
With the addition of the `__eq__` method (#1048), Refs are no longer hashable. This PR should revert to the previous behavior.
=> Allow Refs to be hashable using their data

tests/test_ecs.py, troposphere/ecs.py
AWS released container health checks:
https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-ecs-supports-container-health-checks-and-task-health-mana/
I need this for some apps that don't use a load balancer.
AWS Docs:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_healthcheck
=>  Adding support ECS Container Healthchecks

troposphere/__init__.py
Since the update to use cfn_flip 1.0.2, the `long_form` parameter of `to_yaml` was being incorrectly passed to the `clean_up` parameter of `cfn_flip.to_yaml`. This fixes that, and also add `clean_up` as an actual parameter.
=> Fix to_yaml long_form parameter

troposphere/ec2.py
This fixes the following error:
```
Property validation failure: [Encountered unsupported properties in {/LaunchTemplateData/CreditSpecification}: [CPUCredits]]
```
=> fix casing of CpuCredits

troposphere/serverless.py
Add the missing 'Name' property for AWS::Serverless::Api resource type. (See the document [here](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi))
=> Add 'Name' property for AWS::Serverless::Api

tests/test_template.py, troposphere/__init__.py
This change adds support for `__eq__()`, `__ne__()`, and `__hash__()` to `Template` objects. `to_json()` is used to test for equivalency and to generate the hash.
The following will be available to `Templates`:
- equality testing
```
>>> t1 = Template(Description='foo')
>>> t2 = Template(Description='foo')
>>> t1 == t2
True
```
- inequality testing
```
>>> t1 = Template(Description='foo')
>>> t2 = Template(Description='bar')
>>> t1 == t2
False
```
- usage in sets
```
>>> t1 = Template(Description='foo')
>>> t2 = Template(Description='foo')
>>> len(set([t1, t2]))
1
>>> t1 = Template(Description='foo')
>>> t2 = Template(Description='bar')
>>> len(set([t1, t2]))
2
```
=> Add equality methods to Template

troposphere/__init__.py
By returning the `name` from the add_condition() call, it becomes easier
to re-use a created condition later on, without repeating yourself:
> condition_name = "aCondition"
> template.add_condition(condition_name, Equals(Ref(param), ''))
> template.add_resource(Something("res", Condition=condition_name))
Would become:
> condition_name = template.add_condition("aCondition", Equals(Ref(param), ''))
> template.add_resource(Something("res", Condition=condition_name))
Since add_condition() currently does not return anything, it is highly unlikely this will break anything.
=> Add return value to template.add_condition()

troposphere/__init__.py
When you create a param by passing it a template object, such as
`MyParam = troposphere.Parameter("MyParam", template=t, ...)`
it is added to the template as a resource, not a parameter, as happens when instantiated as follows
`MyParam = template.add_parameter(troposphere.Parameter("MyParam", ...))`
`troposphere.Parameter` extends `troposphere.BaseAWSObject` (through `AWSDeclaration`).
`BaseAWSObject.__init__` does the following
```
if self.template is not None:
self.template.add_resource(self)
```
This means Parameters and Outputs (not sure if there are other types?) add themselves as resources.
Would the best solution to be to break the above code snippet into its own `add_self_to_template` function so it can be overridden by Parameter and Output?
=> Parameter instantiated with template= adds itself as a resource

examples/Serverless_Api_Backend.py, tests/examples_output/Serverless_Api_Backend.template
AmazonDynamoDBFullAccess is required for put or delete, and is consistent with AWS Labs example
=> Changed policy to AmazonDynamoDBFullAccess for delete and put

troposphere/ec2.py
Change corrects the casing for the `CreditSpecification` class's `CPUCredits` object as documented at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance-creditspecification.html
Change also implements a `LaunchTemplateCreditSpecification` class with the correct case for that object.
Fixes #1099
=> Fix CPUCredits casing and create LaunchTemplateCreditSpecification class

troposphere/cognito.py
I was trying to setup a Cognito User Pool and noticed that the UserPool object was missing the `UsernameAttributes` field.
From the docs:
> Specifies whether email addresses or phone numbers can be specified as usernames when a user signs up. Possible values: phone_number or email.
> Required: No
> Type: List of String values
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-usernameattributes
=> Add UsernameAttributes to Cognito

tests/test_codebuild.py, troposphere/codebuild.py
This adds `WINDOWS_CONTAINER` to the valid list of environment types for a CodeBuild `Environment`.
See [here](https://docs.aws.amazon.com/codebuild/latest/userguide/create-project.html#create-project-cli) for docs.
=> Add support for Windows containers in CodeBuild

troposphere/firehose.py
`Prefix` is optional for `S3Configuration`, `S3DestinationConfiguration`, and `ExtendedS3DestinationConfiguration`.
See:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-elasticsearchdestinationconfiguration.html#cfn-kinesisfirehose-deliverystream-elasticsearchdestinationconfiguration-s3configuration
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-redshiftdestinationconfiguration.html#cfn-kinesisfirehose-deliverystream-redshiftdestinationconfiguration-s3configuration
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-splunkdestinationconfiguration.html#cfn-kinesisfirehose-deliverystream-splunkdestinationconf …
=> Made S3 Prefix in Firehose optional

tests/test_validators.py, troposphere/events.py, troposphere/validators.py
This is the enhancement described in the "help wanted" ticket #1052
The behaviour of the validator has been tested agains the values that should be expected.
I'm not entirely sure of the style but this validation will save many users time debugging the cron/rate expressions when using troposphere.
=> Schedule expression validation

tests/test_basic.py, troposphere/__init__.py
When writing reuable methods to add resources and parameters to a template to abstract a common pattern it is often the case that we want to get a parameter that we know may already be inside the template, depending on what the end user has already called.  This PR adds a method which will add a parameter if it's not already there and otherwise return it.
=> Add get_or_add parameter method

troposphere/servicediscovery.py
Documentation for this property is available here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-service.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicediscovery-service-healthcheckcustomconfig.html
It is needed to solve issues with CloudFormation and ServiceDiscovery in ECS, ref: https://forums.aws.amazon.com/thread.jspa?messageID=858305
=> Added HealthCheckCustomConfig to ServiceDiscovery Service

troposphere/sqs.py
SQS queues now support tags (cf. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#cfn-sqs-queue-tags)
=> Tags support for SQS queues

troposphere/ec2.py
- Add PeerRegion propery to VPCPeeringConnection resource
To address following issue:
https://github.com/cloudtools/troposphere/issues/1122
=> VPCPeeringConnection PeerRegion

tests/test_efs.py, troposphere/efs.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-elasticfilesystem-filesystem-provisionedthroughputinmibps
=> Add ThroughputMode and ProvisionedThroughputInMibps to EFS (#1124)

troposphere/validators.py
as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html#cfn-ssm-patchbaseline-operatingsystem , `AMAZON_LINUX_2` is now a valid value
=> AMAZON_LINUX_2 is now supported by SSM

tests/test_codebuild.py, troposphere/codebuild.py
Eventually I see error for `CODECOMMIT` source type:
```
ValueError: Source Location: must be defined when type is CODEPIPELINE
```
That was caused by identity check (`is`) of `source_type` string variable.
```python
>>> source_type = 'CODECOMMIT'
>>> source_type is not 'CODEPIPELINE'
True   # <== What?
>>> id(source_type), id('CODEPIPELINE')
(4430947472, 4432006256)
```
Cheers!
=> [codebuild] source_type - use value comparison instead of identity

examples/CodeDeploy.py, tests/examples_output/CodeDeploy.template, troposphere/codedeploy.py
CloudFormation expects the `OnPremisesInstanceTagFilters` parameter of the `AWS::CodeDeploy::DeploymentGroup` resource to be a list of objects and not a single object, [as seen in the documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-onpremisesinstancetagfilters). This PR fixes that.
I would also like to change the `codedeploy.OnPremisesInstanceTagFilters` to `codedeploy.OnPremisesInstanceTagFilter` (singularis), but not sure how you usually go about doing things like that since it's breaking. If you think it's a good idea, let me know how you usually do it and I will fix it.
=> Update the OnPremisesInstanceTagFilters parameter for AWS::CodeDeploy::DeploymentGroup

tests/test_asg.py, troposphere/autoscaling.py
The validator for AutoScalingGroups assumed that if an AutoScalingRollingUpdate was specified, it would contain the MinInstancesInService attribute, which caused an AttributeError when that argument wasn't passed. However, MinInstancesInService is [optional](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html).
This fixes the assumption that MinInstancesInService is present by adding a default value, and adds tests for the existing intended behavior (to make sure I didn't break it) and to confirm the fix works.
=> Fix AutoScalingRollingUpdate validation failure

troposphere/policies.py
Sept 20th update added a new UpdatePolicy attribute for Elasticache replication groups. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
=> adding UseOnlineResharding policy, per 09/20/2018 update

tests/test_ecs.py, troposphere/ecs.py
This adds support for the newly released `SchedulingStrategy` option in ecs.Service. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-schedulingstrategy for more information on this parameter.
=> Add SchedulingStrategy as a prop to ecs.Service

troposphere/apigateway.py
By supplying value that the previous "[basestring]" accepted, aws would always respond:
"Value of property Parameters must be an object".
The documentation here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html
shows the proper form to be:
"Parameters" : { String:String, ... },
This change allows such values to be set.
=> Use dict for RestApi Parameters

troposphere/ecs.py
Add new properties:
`ContainerName`
`ContainerPort`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-serviceregistry.html
=> Add new properties to ServiceRegistry

troposphere/ec2.py
Adds support for sending logs to S3 in addition to the existing Cloudwatch Logs option
=> Update for new S3 destination option in flow logs

troposphere/apigateway.py
For some reason 3 different properties of the CanarySettings type were
added to ApiGateway:
AWS::ApiGateway::Deployment.DeploymentCanarySettings (3 properties)
- Deployment::DeploymentCanarySettings
AWS::ApiGateway::Stage.CanarySetting (4 properties)
- Stage::CanarySetting
AWS::ApiGateway::Deployment.CanarySetting (3 Properties)
- Deployment.StageDescription::CanarySetting
This attempts to resolve the different properties.
=> Fix issues with CanaraySettings properties

examples/CloudWatchEventsSample.py, tests/examples_output/CloudWatchEventsSample.template
It's necessary Create Permission in CloudWatchEventsSample.py Example to Lambda to work.
=> Add LambdaPermission in Example CloudWatchEventsSample.py

troposphere/apigateway.py, troposphere/applicationautoscaling.py, troposphere/cloudwatch.py, troposphere/ec2.py, troposphere/emr.py, troposphere/glue.py, troposphere/validators.py
fixes #812 + improves validator consistency with AWS naming
- replace `floatingpoint` validator with more valid `double` validator - this is also the naming used in AWS CloudFormation
- update CloudWatch Alarm Threshold datatype to double (according to [documentation](https://docs.aws.amazon.com/de_de/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-threshold))
- update Glue ExecutionProperty MaxConcurrentRuns datatype to positive_integer (according to [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-executionproperty.html#cfn-glue-job-executionproperty-maxconcurrentruns))
=> improve double validation and fix some property datatypes

tests/test_basic.py, troposphere/__init__.py
Fix #1174 
TemplateGenerator was unable to load a template who contains a Fn::Sub with variables
Sample:
```json
{
"AWSTemplateFormatVersion": "2010-09-09",
"Resources": {
"MySNS":{
"Type" : "AWS::SNS::Topic",
"Properties" : {
"DisplayName" : "Display Name",
"TopicName" : {
"Fn::Sub": [ "MySNS-Test-${ABC}",
{
"ABC": "abc"
}
]
}
}
}
}
}
``` 
The issue come from the definition of function `Sub`
As define here:
https://github.com/cloudtools/troposphere/blob/91dc3b5f8916b96ead45783c58d24ce7305c1701/troposphere/__init__.py#L474-L478
When the function is call **from the TemplateGenerator**, it will always have one or two arguments, never more, and if the second argument are present, it will be a **dict** (and it's dict are not unpackaged)
exemple:
```
Sub('MySNS-Test-${ABC}-${DEF}', { 'ABC': …
```
=> Fix #1174 TemplateGenerator fail to parse template Fn::Sub with variable

README.rst, examples/Dlm.py, tests/examples_output/Dlm.template, troposphere/dlm.py
https://aws.amazon.com/about-aws/whats-new/2018/11/introducing-aws-cloudformation-support-for-amazon-data-lifecycle-manager-policies/
=> adding DLM support, per Nov 12 2018 update

troposphere/codepipeline.py
AWS announced support for cross-region actions in CodePipeline. This PR adds the necessary functionality to Troposphere to enable cross-region actions.
Relevant AWS Docs and Announcements:
https://aws.amazon.com/about-aws/whats-new/2018/11/aws-codepipeline-now-supports-cross-region-actions/
https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-create-cross-region.html
=> Add support for multi-region action in CodePipeline

troposphere/autoscalingplans.py, troposphere/validators.py
Adds support for `AWS::AutoScalingPlans::ScalingPlan`
Adds validators for a number of types in `AWS::AutoScalingPlans`
- applicationautoscaling.py
- validators.py
Fixes #1196
=> Adds support for AWS::AutoScalingPlans::ScalingPlan

tests/test_ecs.py, troposphere/ecs.py
AWS DockerVolumeConfiguration expects objects for Labels and DriverOpts.
The current definition leads to a failure when creating the stack : Value of property DriverOpts must be an object,  Value of property Labels must be an object
=> Fix DockerVolumeConfiguration Labels and DriverOpts definition

tests/test_dict.py, troposphere/__init__.py
Ran into an issue in stacker where resources with `Tags` couldn't be
built as `TroposphereType`s because Tags are a subclass of AWSHelperFn.
=> Setup to_dict for Tags AWSHelper

examples/CodeDeploy.py, tests/examples_output/CodeDeploy.template, troposphere/codedeploy.py
Redefine Ec2TagSet class using `Ec2TagSetList` as a property instead of `Ec2TagSet` as the current definition leads to a failure when creating the stack with status `Encountered unsupported property Ec2TagSet`.
=> Fix CodeDeploy EC2TagSet definition

troposphere/cloudwatch.py
Adding [DatapointsToAlarm](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarm-datapointstoalarm) property to AWS::CloudWatch::Alarm.
=> Adding DatapointsToAlarm to AWS::CloudWatch::Alarm

troposphere/ec2.py
`ec2.py`
Adds the missing structure to the classic load balancer config. 
Fixes #1206
=> Fixes LoadBalancersConfig structure

troposphere/ec2.py
`ec2.py`
Sets InstanceType in LaunchTemplateData to not required.
Fixes #1200
=> Sets InstanceType in LaunchTemplateData to not required.

examples/DynamoDB_Tables_OnDemand.py, tests/examples_output/DynamoDB_Tables_OnDemand.template, troposphere/dynamodb.py, troposphere/template_generator.py
I saw that #1239 is also open for the same feature and that there were a couple suggestions made for adding more validation.
I would appreciate feedback on whether my validation logic can be improved since I couldn't find any other set of properties resembling DynamoDB's billing logic now. I looked at the ELBv2 code and was surprised that it doesn't do more deep validation to model the numerous conditionally required properties / mutually exclusive properties.
Although the `ProvisionedThroughput` AWSProperty has become optional unless the billing mode is `PAY_PER_REQUEST` this does not seem to be consistent when using Global Secondary Indexes because that still requires `ProvisionedThroughput` settings. You can confirm this currently in the console because you can't specify on-demand for …
=> Add on-demand billing for DynamoDB tables

examples/Serverless_Deployment_Preference.py, tests/examples_output/Serverless_Deployment_Preference.template, tests/test_serverless.py, troposphere/serverless.py
This PR adds support for the DeploymentPreference option in SAM based templates. 
For more details, see [documentation](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#deploymentpreference-object)
=> Add support for DeploymentPreference to AWS::Serverless::Function

tests/test_elasticloadbalancerv2.py, tests/test_validators.py, troposphere/elasticloadbalancingv2.py, troposphere/validators.py
add possibility to define redirect type with RedirectConfig as
defined in docs: https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Action.html
also add validation to allowed values and combinations of type and
required property
this PR also adds one_of validator to check against list of possible
values
=> extend Action to support Redirect and FixedResponse for AWS::ElasticLoadBalancingV2::ListenerRule

.travis.yml, tests/test_template_generator.py, troposphere/template_generator.py
In macros, a resource type might be defined that needs to be parsed
to be processed. Those resource types might be within the macro transform
or from a different library
=> Add support for extensible resource definitions in template generator

troposphere/rds.py
This was part of the Nov. 19 update:
> Use the DeleteAutomatedBackups property to indicate whether automated backups should be deleted (true) or retained (false) when you delete a DB instance. The default is true.
=> Add DeleteAutomatedBackups to RDS DBInstance

troposphere/template_generator.py
TemplateGenerator seems to generate nested 'Name' sections to Exports in Output section as mentioned in issue #977, this PR should fix the nesting
=> Fix nested 'Name' sections in Output import

tests/test_ec2.py, troposphere/ec2.py
Here is a proposed change to allow ToPort and FromPort to not be required. This should address #1208 and #1245.
Any one want to code review or test?
@daugustus @orenmazor @medwig @phobologic @axelpavageau
=> Allow empty To/From port ranges for SG's for certain IP protocols

troposphere/appstream.py
TypeError: <class 'troposphere.appstream.Fleet'>: fleet.DomainJoinInfo is <class 'troposphere.appstream.DomainJoinInfo'>, expected <class 'troposphere.appstream.DomainJoinInfo'>
Verified locally
=> duplicate classes VpcConfig, DomainJoinInfo

troposphere/inspector.py
…tTarget, per 2019 Jan 17 update
=> ResourceGroupArn is no longer mandatory for AWS::Inspector::AssessmentTarget, per 2019 Jan 17 update

troposphere/autoscalingplans.py
Hello!
First time doing a Pull Request but I found some minor bugs and wanted to help fix.
Cloudformation is just expecting a list instead of 1.
Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-scalinginstruction.html#cfn-autoscalingplans-scalingplan-scalinginstruction-targettrackingconfigurations
Cloudformation allows "ForecastOnly" for the Predictive Scaling Mode.
Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscalingplans-scalingplan-scalinginstruction.html#cfn-autoscalingplans-scalingplan-scalinginstruction-predictivescalingmode
PredefinedLoadMetricSpecification is just a sub property instead of its own object (AWSObject > AWSProperty).
Ref: …
=> Updated autoscalingplans to match cloudformation doco

troposphere/appsync.py
[AppSync pipeline resolver docs](https://docs.aws.amazon.com/appsync/latest/devguide/pipeline-resolvers.html) specify that pipeline resolvers are not attached to any data source, I noticed my Cloudformation templates failing validation because of the non-allowed presence of "DataSourceName" in pipeline resolvers, so I changed the "DataSourceName" field in appsync.py to be be non-mandatory. 
This is my first pull request, so please let me know if I've missed anything.  I didn't open an issue because it seemed like a very small, self-contained fix. 
Thanks for maintaining this project, it's been incredibly helpful!
=> Made DataSourceName non-mandatory in appsync resolver

troposphere/validators.py
Current code seems to assume positive_integer(x) converts to int, while it doesn't.
This problem generates 'Integer must be one of following...' error when the value is in the list because it tries to find a string in an array of ints. 
Other methods such as integer_range do cast correctly, integer_list_item should work the same.
Ran into this issue when creating a LogGroup object with RetentionInDays set to u'7' which should be valid.
=> Small fix in validators.py, integer_list_item_checker should cast to int before checking list contains value

troposphere/events.py
Contains the message group ID to use when the target is a FIFO queue. 
See for more info https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_Target.html#CWE-Type-Target-SqsParameters
=> [events] add SqsParamaters support to Rule Target

tests/test_apigatewayv2.py, troposphere/apigatewayv2.py
Based on updates made to CloudFormation made on the 7th Of Feb, this PR includes apigatewayv2 which is inline with https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-reference-apigatewayv2.html
=> Adding AWS::ApiGatewayV2 Resources

.travis.yml, CONTRIBUTE.rst, setup.py
It will reach its EOL in March 2019, see https://www.python.org/dev/peps/pep-0429/#release-schedule
It has aleady been proposed in cloudtools/troposphere#1295 that Python 3.5 should be the minimal required version.  This PR addresses a low hanging fruit on the road towards this desirable state. :)
=> Drop support for Python 3.4

troposphere/__init__.py
This change just adds a pre-made Ref object for `AWS::Partition`, an unloved and comparatively recent addition to the list of psuedo-parameters.
=> Add psuedo-parameter Ref for AWS::Partition

troposphere/elasticloadbalancingv2.py
Supporting metadata types were added, but can't be used properly without changing the "Type" parameter.
=> Add authenticate-cognito and authenticate-oidc to elb v2 Action's "type" validator

troposphere/constants.py
Based on https://aws.amazon.com/rds/instance-types/
The 'x1' instances listed on the linked page are missing the `db.` prefix.  https://console.aws.amazon.com (create a new oracle instance) and the ['Oracle on Amazon RDS' documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Oracle.html#Oracle.Concepts.InstanceClasses) list them with the prefix.
=> Add constants for missing rds instance types

troposphere/opsworks.py
EngineAttributes variable in the Server class is currently taking a single EngineAttribute object, but Cloudformation allows for a list of attributes, as is necessary when using puppet R10K. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-opsworkscm-server.html#cfn-opsworkscm-server-engineattributes
=> EngineAttributes should take list

tests/test_elasticloadbalancerv2.py, troposphere/elasticloadbalancingv2.py, troposphere/validators.py
Added 'lambda' as a valid target type in a TargetGroup, changing the previously required types (which are only required by 'ip' and 'instance' types) to optional.
Added validation to ensure the now-optional properties are present when needed, and not present when the target type is a lambda.
Apologies for the slightly curt formatting, I was struggling to keep some of the lines under 79 characters :)
=> Added support for lambda in TargetGroup with additional validation

troposphere/codebuild.py
According to documentation, Web Hooks should be written in the form of List of List of WebHooks
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html
API call confirms the structure:
```
"webhook": {
"url": "https://api.github.com/repos/<OMIT>",
"payloadUrl": "https://codebuild.eu-west-1.amazonaws.com/webhooks?t=<OMIT>",
"filterGroups": [
[
{
"type": "EVENT",
"pattern": "PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED",
"excludeMatchedPattern": false
},
{
"type": "ACTOR_ACCOUNT_ID",
"pattern": "ausername",
"excludeMatchedPattern": false
}
],
[
{
"type": "EVENT",
"pattern": "PULL_REQUEST_CREATED, PULL_REQUEST_UPDATED, PULL_REQUEST_REOPENED",
"excludeMatchedPattern": false
},
{
"type": "BASE_REF",
"pattern": …
```
=> Fixed: Codebuild Webhook Filters are to be a list of list of WebhookFilter

troposphere/dms.py
Changing behavior to that of Cloudformation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-username
Given how some Endpoint engine types do not work with the Username property set, this will be more consistent with what's expected.
Related to: https://github.com/cloudtools/troposphere/issues/1019
=> Changing True to False for Username property in Endpoint class

troposphere/serverless.py
According to the SAM documentation (and
https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/sam_resources.py):
* MethodSetting -> MethodSettings
* this is an array of MethodSetting, not a single MethodSetting
=> Fix MethodSettings on AWS::Serverless::Api

troposphere/ecs.py
Noted the Tmpfs prop was missing. Interestingly all the props for TmpFs are optional in the ECS docs!
=> Adds Tmpfs prop to LinuxParameters

tests/test_serverless.py, troposphere/serverless.py
make DefinitionString and DefinitionBody mutually exclusive, but allow no definition
from
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi
```
Swagger specification that describes your API. If neither DefinitionUri
nor DefinitionBody are specified, SAM will generate a DefinitionBody for
you based on your template configuration.
```
=> make DefinitionString and DefinitionBody mutually exclusive

troposphere/ecs.py
ContainerName is a required property according to this documentation: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ProxyConfiguration.html
=> Added missing container name property

troposphere/serverless.py
Role is an optional parameter for DeploymentPreference according to the following section of the AWS SAM documentation:
https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst#traffic-shifting-using-codedeploy
The AWS SAM documentation doesn't seem to be consistent, so I verified in the code itself.
https://github.com/awslabs/serverless-application-model/blob/master/samtranslator/model/preferences/deployment_preference.py#L20
=> Add missing Role property for DeploymentPreference

troposphere/batch.py
Parameters is not a required property as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-parameters
=> Fix Parameters on AWS::Batch::JobDefinition

troposphere/ec2.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-networkinterface.html#cfn-ec2-launchtemplate-networkinterface-interfacetype
=> Add InterfaceType to EC2 LaunchTemplate

troposphere/codebuild.py
Add missing LOCAL location to CodeBuild ProjectCache 
> Location
> 
> Information about the cache location:
> 
> - NO_CACHE or LOCAL: This value is ignored.
>   
> - S3: This is the S3 bucket name/prefix.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectcache.html
=> Add missing LOCAL ProjectCache location option

tests/test_codebuild.py, troposphere/codebuild.py
Fixes a bug introduced here https://github.com/cloudtools/troposphere/pull/1372
Basically while FilterGroups aren't required, the validate() function
was effectively making them required.  This makes it so validate only
validates FilterGroups if they're actually set.
=> Fix bug where FilterGroups were required, when technically they are not

.gitignore, tests/test_validators.py, troposphere/backup.py, troposphere/validators.py
Adds support for AWS::Backup resources added in a [May 23rd update](https://aws.amazon.com/about-aws/whats-new/2019/05/aws-backup-now-supports-aws-cloudformation/).
- [AWS::Backup::BackupPlan](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-backup-backupplan.html)
- [AWS::Backup::BackupSelection](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-backup-backupselection.html)
- [AWS::Backup::BackupVault](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-backup-backupvault.html)
**Note:** These resources are not present in the CloudFormation Resource Specification file as far as I can tell.  I have cut a support case with AWS asking about it, but wanted to get the ball rolling on adding these resources.  Once …
=> Adding AWS::Backup resources from May 23, 2019 update

troposphere/sagemaker.py
A new resource type under SageMaker called AWS::SageMaker::CodeRepository was added. Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-coderepository.html
=> Sagemaker coderepository

troposphere/iam.py
Add the "Tags" property to troposphere's IAM Role definition.
It looks like CloudFormation has started incorporating tags for IAM roles -- the CloudFormation resource specifications for all regions now include a Tags property in the AWS::IAM::Role spec, and stack tags are being applied to generated roles.
=> Add Tags property to IAMRole definition

tests/test_ecr.py, troposphere/ecr.py
ECR added support for tags back in December:
https://aws.amazon.com/about-aws/whats-new/2018/12/amazon-ecr-now-allows-repository-tagging/
Let me know if anything looks out of place. Thanks!
=> Add Tags to ECR Repository definition

troposphere/ec2.py
Per AWS Documentation, EBSBlockDevice supports KmsKeyId now
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html
=> EBSBlockDevice supports KmsKeyId

examples/Backup.py, tests/examples_output/Backup.template, troposphere/backup.py
In the current implementation, the properties RecoveryPointTags and BackupVaultTags are defined as json_checker, which returns a string whereas CloudFormation expects a dict
`BackupVaultTags property should be a key value pair and not a string`
The example template in `tests/examples_output/Backup.template` is actually deploys a BackupPlan and Vault.
=> Fix tags type for AWS Backup resources

examples/Dlm.py, examples/ECRSample.py, examples/EFS.py, examples/ElastiCacheRedis.py, examples/ElasticBeanstalk_Nodejs_Sample.py, examples/IAM_Roles_and_InstanceProfiles.py, examples/IAM_Users_snippet.py, troposphere/compat.py, troposphere/ec2.py, troposphere/ecr.py, troposphere/elasticsearch.py, troposphere/iam.py, troposphere/iot.py, troposphere/iotanalytics.py, troposphere/kms.py, troposphere/s3.py, troposphere/secretsmanager.py, troposphere/sns.py, troposphere/sqs.py
`awacs.aws.PolicyDocument` was introduced in awacs 0.7.1 to prevent confusions with `troposphere.iam.Policy`.  troposphere requires awacs >= 0.8.
=> Prefer awacs.aws.PolicyDocument over awacs.aws.Policy

troposphere/cognito.py
This fixes an invalid type requirement on the 'TemporaryPasswordValidityDays' parameter of the Cognito UserPool Password Policy Object. Setting this to 'float' will invalidate the field if an integer is used, and a float value causes the stack to fail in Cloudformation with an ambiguous error.
=> Fix TemporaryPasswordValidityDays type

troposphere/glue.py
As described in this [issue](https://github.com/cloudtools/troposphere/issues/1481) there is an attribute type mismatch that this patch resolves.
=> updated glue crawler tag attribute to match aws cloudformation doc

examples/MskCluster.py
This typo will make CFN error out about invalid tags which is misleading.
=> Fixed a typo in the ClientBroker's value

troposphere/appsync.py
AppSync [Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-appsync-graphqlapi-additionalauthenticationproviders.html) states that  AdditionalAuthenticationProviders must be of type list. 
Cheers, 
Leo
=> Modified AdditionalAuthenticationProviders field in GraphQlApi to be a list

troposphere/cloudwatch.py
Add _ThresholdMetricId_ for AWS::CloudWatch::Alarm.
Also according to the CloudFormation specification _Threshold_ is not mandatory.
=> Add threshold metric

troposphere/__init__.py
Parameters should be two-levels of nesting, rather than <key, value>. See link for reference:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-findinmap.html
=> Fix naming of parameters in FindInMap helper.

troposphere/ssm.py
Adds `EnableNonSecurity` which is a non-required property for [Rule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ssm-patchbaseline-rule.html)
=> Add missing EnableNonSecurity property to Rule

.travis.yml
[__flake8__](http://flake8.pycqa.org/) runs all the tests that pycodestyle and pyflakes do but also adds the Fxxx errors.
__basestring__ was removed in Python 3.
=> Travis CI: Add flake8 which is a superset of pycodestyle and pyflakes

troposphere/codebuild.py
Was added to documentation in June 2019, see
https://github.com/awsdocs/aws-cloudformation-user-guide/commit/9493fe4d599de6d9f476458f8b849080663b1455#diff-d49f148002b45fafe495c3ea438604f4R176-R187
Current documentation: https://docs.aws.amazon.com/en_pv/AWSCloudFormation/latest/UserGuide/aws-resource-codebuild-project.html#cfn-codebuild-project-sourceversion
=> Add SourceVersion to CodeBuild::Project

troposphere/iam.py
IAM Role now support adding a description to them from a CloudFormation template (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-description), this make it possible to do so in troposphere.
=> Add Description field to IAM Role

troposphere/cognito.py
AWS have changed the type for this property from double to integer, updating type to match.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-refreshtokenvalidity
=> Amend RefreshTokenValidity to match Cognito changes.

troposphere/ec2.py
The placement object is missing a few fields from the upstream
CloudFormation specification:
* Affinity
* HostId
* Tenancy
This commit adds them to the Placement object
Current Placement object specification: https://github.com/cwgem/troposphere/pull/new/updated_launch_template_properties
=> Update placement object

tests/test_mappings.py, troposphere/__init__.py
Multiple `template.add_mapping` calls were squashing the previous key, this patch fixes that
=> Fix mappings

troposphere/cognito.py
cognito.py is missing some critical components that are in the CFT docs but not in cognito. this PR is to add in pool resource servers.
=> cognito is missing UserPoolResourceServer

troposphere/cognito.py
missed that EnabledMfa's needs to be a list of strings.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-enabledmfas
=> uncaught syntax error on EnabledMfa's

troposphere/rds.py
[The documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-scalingconfiguration.html) states that the value "1" is a valid value, which was missing.
> Valid capacity values are 1, 2, 4, 8, 16, 32, 64, 128, and 256
=> Added missing rds scaling configuration capacity

troposphere/guardduty.py
Add property listed here in AWS documentation. : 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-detector.html#cfn-guardduty-detector-findingpublishingfrequency
=> Adding missing property for FindingPublishing

troposphere/apigateway.py
Added in SecurityPolicy as per:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-domainname.html
=> Support for API Gateway SecurityPolicy

troposphere/policies.py
As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html#cfn-attributes-updatepolicy-upgradeelasticsearchdomain
This should allow for in place version upgrade of Elasticsearch clusters
=> Adding update policy that allows for in place upgrade of ES cluster

troposphere/ec2.py
* NoDevice is a string for launch template block device mapping and a null object for EC2 block device mapping
* This addresses the issue by breaking out block device mapping to two separate objects. The EC2 version will keep the original name for backwards compatibility purposes and the launch template version will take up a new name
=> Break out NoDevice property validation (Fixes #1551)

troposphere/ec2.py
Both the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-placementgroup.html) and the spec say it's not required. `gen.py` also outputs it as not required.
=> Strategy in AWS::EC2::PlacementGroup is not required

troposphere/rds.py
This should fix #1520
The property is not in the spec yet, but should already work (source: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/211#issuecomment-570726064)
=> Add CACertificateIdentifier to DBInstance

tests/test_serverless.py, troposphere/serverless.py
Adding AddDefaultAuthorizerToCorsPreflight, ApiKeyRequired, InvokeRole and ResourcePolicy to AWS::Serverless::Api's Auth
=> Updating Serverless Apis's Auth

troposphere/servicediscovery.py
NamespaceId is not strictly required. And NamespaceId is only required once, either there, or in the Service object.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-servicediscovery-service-dnsconfig.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-service.html#cfn-servicediscovery-service-namespaceid
=> NamespaceId is not strictly required

troposphere/secretsmanager.py
CloudFormation supports more TargetTypes than currently present in the
VALID_TARGET_TYPES. This pull request adds the missing values.
List of valid TargetTypes is found at:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html#cfn-secretsmanager-secrettargetattachment-targettype
=> Add missing SecretTargetAttachment TargetTypes

troposphere/autoscaling.py
Ignore If expression in validation of AutoScalingRollingUpdate min instances
Same thing as in https://github.com/cloudtools/troposphere/pull/446, but only for min instances instead of max instances.
=> Ignore If expression in validation of AutoScalingRollingUpdate min instances

troposphere/elasticloadbalancingv2.py
For Issue: https://github.com/cloudtools/troposphere/issues/1554
=> Added support for ForwardConfig in Listener

tests/test_rds.py, troposphere/rds.py
Fixes https://github.com/cloudtools/troposphere/issues/1600
We are using troposphere and stacker to spin up Aurora Serverless
clusters using Postgresql and received errors that our MaxCapacity
arguments to ScalingConfiguration were failing validation even though
AWS documentation showed them to be correct.
This adds the valid options for postgres as well as mysql
=> fix: include valid postgres capacity configurations

troposphere/ec2.py
fixes https://github.com/cloudtools/troposphere/issues/1621
=> AWS::EC2::SecurityGroupIngress.SourcePrefixListId

troposphere/acmpca.py
Subject should be AWSProperty not AWSObject
[aws-resource-acmpca-certificateauthority](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificateauthority.html)
Certificate should be AWSObject not AWSProperty
[aws-resource-acmpca-certificate](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-acmpca-certificate.html )
=> Fixes to acmpca

troposphere/wafv2.py
- Several classes were subclasses of AWSObject when they should be  subclasses of AWSProperty.
- Several classes have arguments that are lists. These args were defined via intermediate classes that in turn defined the lists. This was incorrect. The classes should accept the lists directly.
I fixed the list arguments for these classes:
GeoMatchStatement
AndStatementOne
OrStatementOne
AndStatementTwo
OrStatementTwo
I remove these unnecessary intermediate list classes:
CountryCodes
StatementTwos
StatementThrees
=> Fix several problems in wafv2

examples/IoTAnalytics.py, examples/IoTSample.py, tests/examples_output/IoTAnalytics.template, tests/examples_output/IoTSample.template, troposphere/iot.py, troposphere/iotanalytics.py
A number of fixes for IoT Analytics: Datastore AWSProperty name duplicated/shadowed the Datastore AWSObject name; RetentionPeriod class was listed twice, added ChannelStorage and DatastoreStorage AWSProperties.
Adds an example IoTAnalytics.py template.
I think this brings IoTAnalytics up to sync with CloudFormation - I've started using it to make some IoTAnalytics resources.
Also added IotAnalytics and StepFunctions to iot.Action property for iot.py
=> IoT Analytics fixes and additions

troposphere/codebuild.py
AWS CodeBuild added support for the SECRETS_MANAGER environment variable type. troposphere should be able to support it as well.
=> add secrets manager type to codebuild environment variable types

README.rst, troposphere/codeguruprofiler.py
=> Adding AWS::CodeGuruProfiler::ProfilingGroup resource, per March 19, 2020 update

troposphere/servicecatalog.py
=> Adding AWS::ServiceCatalog::LaunchRoleConstraint props, per April 2, 2020 update

troposphere/securityhub.py
=> AWS::SecurityHub::Hub Tags uses the wrong format

troposphere/ec2.py
=> Adding AWS::EC2::Volume props, per March 26, 2020 update

troposphere/wafv2.py
Potential fix for issue https://github.com/cloudtools/troposphere/issues/1677
Change RegularExpressionList to take a list of Regex and set required True as per the documentation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-regexpatternset.html#cfn-wafv2-regexpatternset-regularexpressionlist
=> RegularExpressionList fix

examples/AuroraServerlessRDS_SecretsManager.py, tests/examples_output/AuroraServerlessRDS_SecretsManager.template
The examples are always helpful so I wanted to show one using Aurora Serverless (MySQL). It is using Secrets Manager to generate / store the DB Admin's Master Password as well.
I ran the tests locally and it looks OK:
```
test_template_generator (tests.test_examples_template_generator.test_AuroraServerlessRDS_SecretsManager) ... ok
```
This is my first PR here so if I need to change anything please let me know! Thanks :)
=> Add sample Aurora Serverless RDS template

troposphere/stepfunctions.py
note that https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-definitionsubstitutions.html is currently empty
=> Updating AWS::StepFunctions::StateMachine props, per May 21, 2020 update

troposphere/wafv2.py
Currently, the wafv2 module defines `ExcludedRule` and wrapper object `ExcludedRules`:
```python
ManagedRuleGroupStatement(
ExcludedRules=ExcludedRules(
ExcludedRules=[ExcludedRule(), ExcludedRule()]
)
)
```
This outputs something like:
```json
"ManagedRuleGroupStatement": {
"ExcludedRules": {
"ExcludedRules": 
[
{
"Name": "SizeRestrictions_BODY"
}
]
},
"Name": "AWSManagedRulesCommonRuleSet",
"VendorName": "AWS"
}
```
However, this results in a "Internal Failure" error in CloudFormation:
Correct CFT is something like this, without the double-wrapped `ExcludedRules`.
```json
"ManagedRuleGroupStatement": {
"ExcludedRules": [
{
"Name": "SizeRestrictions_BODY"
}
],
"Name": "AWSManagedRulesCommonRuleSet",
"VendorName": "AWS"
}
```
Proposed PR fixes this syntax.
=> Fix waf excluded rules

tests/test_codebuild.py, troposphere/codebuild.py
This adds ARM_CONTAINER and  LINUX_GPU_CONTAINER to the valid list of environment types for a CodeBuild Environment.
=>  Add support for ARM and GPU containers for CodeBuild

troposphere/stepfunctions.py
DefinitionSubstitutions is declared in the documentation for AWS::StepFunctions::StateMachine as a map (string to string).
Tested to work with entries such as
```
stepfunctions.StateMachine(
"ExampleStepFunction",
DefinitionString=json.dumps({
"Comment": "Ohayo gozaimasu",
"StartAt": "Begin",
"States": {
"Begin": {
"Type": "Task",
"Resource": "${arn_1}",
},
},
}),
DefinitionSubstitutions={
"arn1": "arn...",
},
RoleArn=...
)
```
=> Convert stepfunctions.DefinitionSubstitutions to dict

troposphere/serverless.py
I found these were missing, so I implemented them. I hope they find their way into the core so I can stop using a shim.  ;)
=> Added Serverless::Application and Serverless ApplicationLocation

troposphere/ecs.py
Tested and functional with following code sample:
```
Cluster(
ROOT_CLUSTER_NAME,
template=template,
ClusterName=If(CLUSTER_NAME_CON_T, Ref(AWS_STACK_NAME), Ref(CLUSTER_NAME_T)),
DependsOn=depends_on,
CapacityProviders=["FARGATE", "FARGATE_SPOT"],
DefaultCapacityProviderStrategy=[
CapacityProviderStrategyItem(
Weight=2,
CapacityProvider="FARGATE_SPOT"
),
CapacityProviderStrategyItem(
Weight=1,
CapacityProvider="FARGATE"
)
]
)
```
Generated following template (snippet):
```
Resources:
EcsCluster:
DependsOn:
- vpc
Properties:
CapacityProviders:
- FARGATE
- FARGATE_SPOT
ClusterName: !If
- SetClusterNameFromRootStack
- !Ref 'AWS::StackName'
- !Ref 'EcsClusterName'
DefaultCapacityProviderStrategy:
- CapacityProvider: FARGATE_SPOT
Weight: 2
- CapacityProvider: FARGATE
Weight: 1
Type: …
```
=> Added capacity providers for ECS Cluster

troposphere/rds.py
Cloudformation seems to throw an error when a DBProxyTargetGroup lacks
the TargetGroupName property.  [The Cloudformation documentation for the
DBProxyTargetGroup resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbproxytargetgroup.html) has no reference to this property, but the
[examples on the page for DBProxy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbproxy.html#aws-resource-rds-dbproxy--examples) shows the TargetGroupName being set to
"default" in the DBProxyTargetGroup resource.
=> Add required TargetGroupName to AWS::RDS::DBProxyTargetGroup

troposphere/sagemaker.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpointconfig.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-endpoint.html
In the CloudFormation documentation, the `Tags` property is listed as optional for SageMaker's `Endpoint` and `EndpointConfig`. This PR changes Troposphere to reflect that.
=> SageMaker: Mark tags props as optional, per AWS documentation.

troposphere/servicecatalog.py
fixes https://github.com/cloudtools/troposphere/issues/1757
[`AWS::ServiceCatalog::LaunchRoleConstraint.RoleArn`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-launchroleconstraint.html#cfn-servicecatalog-launchroleconstraint-rolearn)
=> AWS::ServiceCatalog::LaunchRoleConstraint.RoleArn not required

troposphere/firehose.py
fixes https://github.com/cloudtools/troposphere/issues/1753
[`AWS::KinesisFirehose::DeliveryStream.ExtendedS3DestinationConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-extendeds3destinationconfiguration.html)
[`AWS::KinesisFirehose::DeliveryStream.S3DestinationConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-s3destinationconfiguration.html)
=> AWS::KinesisFirehose::DeliveryStream BufferingHints and CompressionFormat not required in S3DestinationConfigurations

troposphere/firehose.py
fixes https://github.com/cloudtools/troposphere/issues/1744
[`AWS::KinesisFirehose::DeliveryStream.ElasticsearchDestinationConfiguration.TypeName`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisfirehose-deliverystream-elasticsearchdestinationconfiguration.html#cfn-kinesisfirehose-deliverystream-elasticsearchdestinationconfiguration-typename)
=> AWS::KinesisFirehose::DeliveryStream.ElasticsearchDestinationConfiguration.TypeName not required

troposphere/stepfunctions.py
fixes https://github.com/cloudtools/troposphere/issues/1764
[`AWS::StepFunctions::StateMachine.DefinitionString`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-definitionstring)
[`AWS::StepFunctions::StateMachine.S3Location.Version`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-s3location.html#cfn-stepfunctions-statemachine-s3location-version)
=> AWS::StepFunctions::StateMachine DefinitionString and S3Location.Version not required

troposphere/ec2.py
Add SourcePrefixListId to combined SecurityGroupRule for consistency
with SecurityGroupIngress and SecurityGroupEgress
=> Add SourcePrefixListId to SecurityGroupRule

troposphere/elasticsearch.py
[`AWS::Elasticsearch::Domain`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html)
fixes #1774
=> AWS::Elasticsearch::Domain.AdvancedSecurityOptions

troposphere/glue.py
fixes https://github.com/cloudtools/troposphere/issues/1776
https://github.com/aws-cloudformation/cfn-python-lint/pull/1673
[`AWS::Glue::Connection.ConnectionInput.ConnectionType`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-connectiontype)
=> AWS::Glue::Connection.ConnectionInput.ConnectionType AllowedValues expansion

troposphere/awslambda.py, troposphere/serverless.py
Adding more supported properties for `KinesisEvent`:
- BisectBatchOnFunctionError
- DestinationConfig
- Enabled
- MaximumBatchingWindowInSeconds
- MaximumRecordAgeInSeconds
- MaximumRetryAttempts
- ParallelizationFactor
Also make not required `OnFailure` and `OnSuccess` for *DestinationConfig* according to [CloudFormation specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventinvokeconfig-destinationconfig.html) this makes possible to use *DestinationConfig* for [Lambda EventSourceMapping](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html#cfn-lambda-eventsourcemapping-destinationconfig) and [Kinesis Destination](https://docs.aws.amazon.com/serverless-application-model/latest/developer …
=> Add properties for kinesis event source

troposphere/serverless.py
The parameter was missing.
Reference: [Cloudformation documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html)
=> Support for OpenApiVersion in serverless.Api

troposphere/eks.py, troposphere/fsx.py
Hey guys, First time contributing. So please let me know if I'm missing anything.
I've added the missing LaunchTemplate property to EKS Nodegroup.
Let me know if you need me to make any updates or if you have any questions.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html
=> Add LaunchTemplate property to EKS NodeGroup

troposphere/secretsmanager.py
This property is only conditionally required. Per CloudFormation, "Transform AWS::SecretsManager-2020-07-23 failed with: Can only specify either HostedRotationLambda or RotationLambdaARN."
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html#cfn-secretsmanager-rotationschedule-rotationlambdaarn
=> AWS::SecretsManager::RotationSchedule.RotationLambdaARN not required

examples/ECSFargate.py, tests/examples_output/ECSFargate.template, tests/test_ecs.py, troposphere/ecs.py
Switch to the [AWS documented capitalization](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-awsvpcconfiguration.html) to avoid the following error (and related):
```
E3002 Invalid Property Resources/BulkScannerService/Properties/NetworkConfiguration/AwsvpcConfiguration
```
[which appears in `cfn-lint==0.36.1`](https://github.com/aws-cloudformation/cfn-python-lint/issues/1706)
I attempted to run the unit tests but in vera case bottomed out with
```
======================================================================
ERROR: test_CustomResource (tests.test_examples.TestExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
File …
```
=> Fix capitalization in AwsVpcConfiguration

troposphere/appmesh.py
Untested yet, adding support for AWS AppMesh Gateway:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appmesh-virtualgateway.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appmesh-gatewayroute.html
Unfortunately, the Listerners, Match and actions for HTTP and gRPC are not exactly the same as the ones for the Nodes/Router so had to re-implement these properties on their own. Re-used existing AWSProperty whenever possible.
=> AppMesh Gateway support

troposphere/athena.py
According to the aws cloudformation docs for athena workgroup, they are expecting an array of key-value pair of type `Tags`
=> Fixing tags data type for the issue #1784

tests/test_serverless.py, troposphere/serverless.py
Serverless APIs can have Endpoint Configurations set that are more complex than a standard String
=> Added Types to EndpointConfiguration

troposphere/elasticloadbalancingv2.py, troposphere/fsx.py
Allow TargetType to be Ref items, such as `Ref('AWS::NoValue')`, as well as parameters.
This will not allow using `None`, but one would argue `Ref('AWS::NoValue')` would be a better choice.
Also today, when trying to use `None` (at least in python 2.7), you would get the error:
`TargetType is <type 'NoneType'>, expected <type 'basestring'>`
Fixes #1539
=> Fix target type validation

troposphere/cloudfront.py, troposphere/validators.py
Added support for Cloudfront CachePolicy and OriginRequestPolicy with proper validators.
Tested creation with a template containing both CachePolicy and OriginRequestPolicy.
Note:
You cannot set MaxTLL = MinTLL = DefaultTTL = 0 in CachePolicyConfig.
If you do this CloudFormation give error ("Invalid request provided: AWS::CloudFront::CachePolicy").
By WebGui if you set all to zero you are no more able to configure ParametersInCacheKeyAndForwardedToOrigin's parameters as Cookie, Headers and QueryStrings.
This is probably the root cause of the error.
(ParametersInCacheKeyAndForwardedToOrigin is always required, so omitting it is not a solution)
In that case just set MaxTLL to one (maybe AWS will fix this in the future).
=> Cloudfront cache and origin policy

examples/ECSFargate.py, tests/examples_output/ECSFargate.template, tests/test_ecs.py, troposphere/ecs.py
See comment by Pat Myron from AWS (https://github.com/cloudtools/troposphere/pull/1788#issuecomment-702982230):
This property was accidentally uppercased during the migration of
`AWS::ECS::Service` to the CloudFormation Registry in Resource
Specification 18.4.0 and reverted in 18.6.0. It should probably be
kept lowercase
For more details see also aws-cloudformation/cfn-python-lint#1706
=> Revert "Fix capitalization in AwsVpcConfiguration (#1788)"

troposphere/validators.py
Update canary version validation to include the new synthetics canary runtimes: 'syn-nodejs-2.0', 'syn-nodejs-2.0-beta'
[`AWS::Synthetics::Canary.RuntimeVersion`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-synthetics-canary.html#cfn-synthetics-canary-runtimeversion)
=> AWS::Synthetics::Canary.RuntimeVersion AllowedValues expansion

troposphere/ecs.py, troposphere/validators.py
PR addresses the following:
https://github.com/cloudtools/troposphere/issues/1806
https://github.com/cloudtools/troposphere/issues/1807
=> Fix issues with ecs.EFSVolumeConfiguration usage

troposphere/elasticsearch.py
fixes #1779 
Update elasticsearch.py to support Elasticsearch Domain parameter DomainEndpointOptions
Documentation references below:
ES Domain: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html
DomainEndpointOptions: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-domainendpointoptions.html
=> AWS::Elasticsearch::Domain.DomainEndpointOptions

troposphere/cloudfront.py
Supporting CloudFormation documentation for the property: [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-lambdafunctionassociation.html#cfn-cloudfront-distribution-lambdafunctionassociation-includebody](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-lambdafunctionassociation.html#cfn-cloudfront-distribution-lambdafunctionassociation-includebody)
=> AWS::CloudFront::Distribution.LambdaFunctionAssociation.IncludeBody

troposphere/validators.py
[`AWS::ImageBuilder::ImageRecipe.EbsInstanceBlockDeviceSpecification.VolumeType`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-imagebuilder-imagerecipe-ebsinstanceblockdevicespecification.html#cfn-imagebuilder-imagerecipe-ebsinstanceblockdevicespecification-volumetype)
[could be sourced automatically from botocore](https://github.com/aws-cloudformation/cfn-python-lint/pull/1682/)
=> AWS::ImageBuilder::ImageRecipe.EbsInstanceBlockDeviceSpecification.VolumeType AllowedValues expansion (io2)

troposphere/codebuild.py
[`AWS::CodeBuild::Project.Environment.Type`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-environment.html#cfn-codebuild-project-environment-type)
[could be sourced automatically from botocore](https://github.com/aws-cloudformation/cfn-python-lint/pull/1682)
=> AWS::CodeBuild::Project.Environment.Type AllowedValues expansion (WINDOWS_SERVER_2019_CONTAINER)

troposphere/glue.py
[`AWS::Glue::Connection.ConnectionInput.ConnectionType`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html#cfn-glue-connection-connectioninput-connectiontype)
[could be sourced automatically from botocore](https://github.com/aws-cloudformation/cfn-python-lint/pull/1682/)
=> AWS::Glue::Connection.ConnectionInput.ConnectionType AllowedValues expansion (NETWORK)

troposphere/firehose.py
Kinesis Firehose Delivery Stream is missing tags option. When a stream is created, consumer would like to add some tagging to the resource.
=> AWS::KinesisFirehose::DeliveryStream.Tags

troposphere/validators.py
[`AWS::EC2::VPCEndpoint.VpcEndpointType`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-vpcendpointtype)
[could be sourced automatically from botocore](https://github.com/aws-cloudformation/cfn-python-lint/pull/1682)
=> AWS::EC2::VPCEndpoint.VpcEndpointType AllowedValues expansion (GatewayLoadBalancer)

troposphere/s3.py
Add ReplicaModifications, which is introduced in https://aws.amazon.com/about-aws/whats-new/2020/12/amazon-s3-replication-adds-support-two-way-replication/.
Reference:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-replicamodifications.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-sourceselectioncriteria.html
=> Add ReplicaModifications of s3

troposphere/emr.py
Added ability to add AllocationStrategy to the EMR instance fleet configuration. This change also adds OnDemandSpecification to InstanceFleetProvisioningSpecifications
=> Add AllocationStrategy to EMR instance fleet configuration

examples/Backup.py, tests/examples_output/Backup.template, troposphere/backup.py
AWS Backup now supports cross-account backups. This is supported by the new CloudFormation property CopyActions for the BackupRuleResourceType.
=> Add CopyActions prop to BackupRuleResourceType for Backup

troposphere/autoscaling.py
Trivial support for new boolean CapacityRebalance property of AutoScalingGroup objects [added by AWS on 04 Nov](https://aws.amazon.com/blogs/compute/proactively-manage-spot-instance-lifecycle-using-the-new-capacity-rebalancing-feature-for-ec2-auto-scaling/).
Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-capacityrebalance
Thank you. :heart:
=> AWS::AutoScaling::AutoScalingGroup.CapacityRebalance

tests/test_awslambda.py, troposphere/awslambda.py
This has not been added to [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html) yet but, the options are present in the [API documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax. When provided in a CloudFormation template in one of the regions that supports this feature it is working.
```yaml
Resources:
TestFunction:
Type: AWS::Lambda::Function
Properties:
Code:
ImageUri: !Ref ImageUri
Description: This is just a test.
PackageType: Image
Role: !Ref Role
```
=> AWS::Lambda::Function support for container image deployment package

troposphere/cloudfront.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-origin.html#cfn-cloudfront-distribution-origin-originshield
Not add the validate for shield region as all other regions in other stacks not using validation.
=> AWS::CloudFront::Distribution.Origin.OriginShield

troposphere/helpers/userdata.py
There is a small typo in troposphere/helpers/userdata.py.
Should read `should` rather than `shoud`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, shoud -> should

troposphere/s3.py
AWS added a new field `BucketKeyEnabled`, which is an optional boolean. 
Please see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-serversideencryptionrule.html
=> AWS::S3::Bucket ServerSideEncryptionRule: add property BucketKeyEnabled

troposphere/__init__.py
Fixes https://github.com/cloudtools/troposphere/issues/1089
=> added sort flag to yaml method arguments

troposphere/kinesisanalyticsv2.py
This PR fixing bug in field definition of PropertyGroup in kinesisanalyticsv2 module.
Reference:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesisanalyticsv2-application-propertygroup.html
CF type is Json, bu `json_checker` represents String with json content. Correct type in troposphere to represent CF Json type is `dict`.
For example, in code pipeline Action CF:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html
`Configuration` field is of type `Json`, so in troposphere:
https://github.com/cloudtools/troposphere/blob/master/troposphere/codepipeline.py
field type is `dict`, what is correct.
I tested this change in my project using version from my fork and it works correctly.
=> change PropertyMap in kinesisanalyticsv2 PropertyGroup to dict

troposphere/elasticsearch.py
This adds on to options available for https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-domainendpointoptions.html
=> Adding optional domain options for custom endpoints

troposphere/ec2.py
This allows setting the `Throughput` field for the AWS `gp3` ebs volumes when creating an `Ec2EBSBlockDevice`.
=> Support Throughput for gp3 ebs volumes

README.rst, troposphere/mwaa.py
For this issue: https://github.com/cloudtools/troposphere/issues/1855
My first time contributing to this library, so I'm guessing I'm missing some things. But hopefully someone can use this as a starting point or at least check that I added things correctly!
=> AWS::MWAA Adding for managed airflow

examples/DynamoDB_Table_With_KinesisStreamSpecification.py, tests/examples_output/DynamoDB_Table_With_KinesisStreamSpecification.template, troposphere/dynamodb.py
DynamoDB added KDS integration a few months back. Just this past week they added support to CloudFormation. We've been eagerly waiting on this for our application. 
See: [DynamoDB table KinesisStreamSpecification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-kinesisstreamspecification) 
This is my first pull request to this project so please provide me with any and all feedback. I'm happy to do what is necessary to get this feature added. Thank you!
=> Adding support for using KinesisStreamSpecification with DynamoDB

troposphere/ec2.py
noticed the [throughput](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#cfn-ec2-ebs-volume-throughput) property is missing from the AWS::EC2::Volume resource object.
couldn't find any existing unit tests for this resource.
=> ec2 volume throughput

troposphere/ec2.py
Add `MulticastSupport` attribute to `TransitGateway` that is currently supported by CloudFormation. Tested and validated as working.
=> Transit-Gateway MulticastSupport

troposphere/helpers/userdata.py
Imports userdata from a file, using `Sub` for replacing inline variables such as `${AWS::Region}`.
Useful with a userdata script that looks like this:
```bash
#!/bin/bash -ex
echo Region: ${AWS::Region}
...
```
Unlike `from_file()`, doesn't do any text processing.
=> Add helpers.userdata.from_file_sub()

troposphere/ecs.py
Adds ephemeral storage property for use with Fargate as documented here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-ephemeralstorage.html
=> Add fargate ephemeral storage property

troposphere/rds.py
`GlobalClusterIdentifier` is missing from `troposphere.rds.DBCluster`.
From CloudFormation Resource Specification:
```json
"GlobalClusterIdentifier": {
"Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-globalclusteridentifier",
"PrimitiveType": "String",
"Required": false,
"UpdateType": "Conditional"
},
```
From the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-globalclusteridentifier):
> If you are configuring an Aurora global database cluster and want your Aurora DB cluster to be a secondary member in the global database cluster, specify the global cluster ID of the global database cluster. To define the primary database …
=> AWS::RDS::DBCluster: add missing GlobalClusterIdentifier parameter

troposphere/batch.py
Some properties are no longer required (at least when using Fargate). Source:
- `ContainerProperties.Memory`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-memory
- `ContainerProperties.Vcpus`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-vcpus
- `ComputeEnvironment.ServiceRole`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-computeenvironment.html#cfn-batch-computeenvironment-servicerole
I've successfully deployed patched resources without those properties.
=> [batch] Update required properties

troposphere/ec2.py
Newly released property for NatGateway to remove the internet gateway requirement when using NAT Gateway for internal natting. See updated Cloudformation docs:https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html
=> Add ConnectivityType property for NatGateway

troposphere/codestarconnections.py
As per Amazon's [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codestarconnections-connection.html#aws-resource-codestarconnections-connection-properties) the following provider types are allowed:
- Bitbucket
- GitHub
- GitHubEnterpriseServer
=> VALID_CONNECTION_PROVIDERTYPE to list and added GH and GH Enterprise

troposphere/eks.py
Correct key is not `Name` it is `Key`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-taint.html
=> fix(AWS::EKS::Nodegroup.Taints): use the correct key for taints 

troposphere/batch.py
A property is necessary (but not required) when using Batch on Fargate:
`ContainerProperties.NetworkConfiguration`:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-networkconfiguration
=> [batch] Update ContainerProperties properties

troposphere/logs.py
This attribute is supported by CloudFormation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#aws-resource-logs-loggroup-syntax
=> Add KmsKeyId Attribute to LogGroup

troposphere/validators.py
AWS now supports SIGN_VERIFY as a KMS key usage.
=> Added Sign and Verify key usage

troposphere/autoscaling.py
As per AWS document:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-launchtemplateoverrides.html
=> Allow LaunchTemplateSpecification in LaunchTemplateOverrides

troposphere/autoscaling.py
This was added to Cloudformation on June 18. (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-scheduledaction.html
=> Add TimeZone property to autoscaling.ScheduledAction (AWS::AutoScaling::ScheduledAction)

tests/test_serverless.py, troposphere/serverless.py
Add support for AWS::Serverless::HttpApi
[sam-resource-httpapi](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html)
=> Add serveless HttpApi class

troposphere/dynamodb.py
The duplicate TargetTrackingScalingPolicyConfiguration class defined in dynamodb causes type assertions to fail
`TypeError: <class 'troposphere.dynamodb.CapacityAutoScalingSettings'>: None.TargetTrackingScalingPolicyConfiguration is <class 'troposphere.dynamodb.TargetTrackingScalingPolicyConfiguration'>, expected <class 'troposphere.dynamodb.TargetTrackingScalingPolicyConfiguration'>`
=> Remove duplicate TargetTrackingScalingPolicyConfiguration from dynamodb.py

troposphere/cloudfront.py, troposphere/validators.py
Adding Changes per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-responseheaderspolicy.html
=> Added Cloudfront Response Header changes per Nov 4 updates.

troposphere/serverless.py
Per the [SAM Developer Guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-architectures)
=> Add Architectures to AWS::Serverless::Function

CHANGELOG.rst
Changes:
- Silenced a Sphinx error by closing an unclosed emphasis markup.
- Fixed 3.0.0 release notes formatting.
The 3.0.0 releases notes were mostly rendering as just a paragraph, or
an incomplete list with unexpected rendering of the literal block. These changes fix the
formatting so that the 3.0.0 release notes Breaking Changes, and Changes
lists are now subsections of the 3.0.0 section. The second bullet point
in the Breaking Changes section was also throwing unexpected indentation
errors. This has been resolved now, and the section is rendering as a
literal box as expected.
=> CHANGELOG.rst Formatting Fixes

troposphere/networkfirewall.py
The logging configuration was not correct per CloudFormation documentation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-networkfirewall-loggingconfiguration.html
=> NetworkFirewall - Fixed LoggingConfiguration

troposphere/eks.py
Adding `UpdateConfig` to NodeGroup, [see](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-nodegroup.html#cfn-eks-nodegroup-updateconfig)
=> Add UpdateConfig to NodeGroup

.pre-commit-config.yaml, CONTRIBUTE.rst, requirements-dev.txt
Got bitten by this on my last PR - so figured I'd give it a little automation for the next person to come along (especially if that should happen to be me!)
Pretty simple to start, but can be expanded with additional checks down the line if desired.
=> pre-commit checks for black+isort

setup.cfg, troposphere/py.typed
Starting with release version `3.2.0` we began getting `mypy` errors that did not used to exist when using version `3.1.1`.
As part of the [commit that introduced](https://github.com/cloudtools/troposphere/commit/07b984f5d1033690878ce2112ebd2281ab8dc560) the new `PropsDictType` variable, the `troposphere/py.typed` file was also added. In accordance with [PEP 561](https://www.python.org/dev/peps/pep-0561/), the presence of this file should be used when the underlying code has types or stubs defined. The example below demonstrates how the `py.typed` can cause `mypy` to throw errors that did not trigger before.
```python
from troposphere import Template
import troposphere.ec2 as ec2
t = Template()
instance = ec2.Instance("myinstance")
instance.ImageId = "ami-951945d0"
instance.InstanceType = …
```
=> mypy errors starting with release 3.2.0

.editorconfig, .github/workflows/tests.yml, .gitignore, Makefile, package-lock.json, package.json, pyproject.toml, troposphere/__init__.py, troposphere/type_defs/__init__.py, troposphere/type_defs/compat.py, troposphere/type_defs/protocols.py, troposphere/validators/__init__.py
Adds type annotations for classes and functions in (and used in) the root of the project as a first pass at adding type annotations for this project.
This also implements a type checker (pyright) that is set to `off` except for the files that were updated to include type annotations. For those files, it is set to `strict`.
=> add type annotations for base classes & some validators

troposphere/__init__.py
See also https://github.com/cloudtools/troposphere/pull/2013#discussion_r838745452
=> Let type hints show that lists of resources, parameters, and outputs are also valid

troposphere/validators/ssm.py
According to the CloudFormation documentation, a few more values are supported now for `OperatingSystem`.
[Source](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html)
=> Update SSM Patch Baseline OS validator

tests/test_ssm.py, troposphere/ssm.py, troposphere/validators/ssm.py
Fixes #2053
@pmau could you review and verify this fixes your use case?
=> Allow json/yaml strings for SSM Document.Content property

tests/test_serverless.py, troposphere/serverless.py
Closes #2063
I tried extracting the  function to `troposhpere.validators.__init__.py` as it made more sense to have it there, but its dependence on `AWSHelperFn` created a circular import with `troposhpere.__init__.py`. Fixing that would require picking apart the entire `troposhpere.__init__.py` file.
=> Add support for list types and validator functions in GlobalsHelperFn type check

examples/BatchEventSnsLambda.py, tests/examples_output/BatchEventSnsLambda.template
Extend the official tutorial to be more close to production, the original tutorial is located at:
https://docs.aws.amazon.com/batch/latest/userguide/batch_sns_tutorial.html
This example would send a successful job every 1 minute and failed job every 3 minutes and the failed jobs would invoke the lambda function through SNS.
=> An example of SNS alert for failed batch job events

troposphere/validators/elasticsearch.py
Referenced https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-opensearch-service-support-ebs-gp3-volume-type/
=> Allow setting hosted elasticsearch volume_types to gp3

tests/test_language_extensions.py
See https://aws.amazon.com/about-aws/whats-new/2022/09/aws-cloudformation-new-language-extensions-transform/
I've take the example from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-languageextension-transform.html to see if that works.
At least the combination of `AWS::LanguageExtensions` with the `AWS::Serverless` transform and globals needs a bit of work.  The globals checks don't work with multiple transforms.  https://github.com/cloudtools/troposphere/blob/759496c4d2ed3fec6fcb7315b98fa9bf7e2335b2/troposphere/__init__.py#L834-L850
=> Add a simple test for the new AWS::LanguageExtensions transform

scripts/patches/lakeformation.py, troposphere/lakeformation.py
Use PrincipalResource for the PrincipalPermissions.Resource Property to remove a naming conflict with Permissions.Resource.
Fixes #2073
=> Lakeformation: remove ResourceProperty naming conflict

troposphere/validators/kinesisanalyticsv2.py
Kinesis Data Analytics now supports Flink 1.15 runtime, see 
https://docs.aws.amazon.com/kinesisanalytics/latest/java/flink-1-15-2.html and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalyticsv2-application.html#cfn-kinesisanalyticsv2-application-runtimeenvironment
This PR adds support for FLINK-1_15 runtime.
Fix https://github.com/cloudtools/troposphere/issues/2105
=> Add support for Flink 1.15 runtime environment 

troposphere/validators/rds.py
We use a read-replica MySQL instance to ingest data utilizing a SaaS vendor.
This SaaS vendor requires binary logging on the read-replica instance to enable the replication of data from the RR. When using CloudFormation, without the `BackupRetentionPeriod`, binary logging is disabled on the read-replica instance. 
To enable binlogging using the current version of troposphere, a console change must be made post deployment, or an aws-cli call to enable backup retention from a non-zero value, due to incorrect `invalid_replica_properties`.
This is not ideal because any subsequent CloudFormation changes will revert this to a 0 value, breaking binlog configuration. This change is to be able to enable binary logging with CloudFormation. 
AWS Documentation …
=> Modify `SourceDBInstanceIdentifier` validator to allow `BackupRetentionPeriod`

troposphere/fsx.py, troposphere/validators/fsx.py
Bring in `PerUnitStorageThroughput` numbers and checking logic to support the `PERSISTENT_2` `DeploymentType` for FSx/Lustre.
=> Support for FSx/Lustre PERSISTENT_2 DeploymentType

troposphere/__init__.py
My use case is something like
```python
t.add_output([
Output(
...,
Export=Export(Join(":", ["some", "stuff"]))
)
])
```
=> Be more lenient about types for Export

.github/workflows/maintenance.yaml, .github/workflows/tests.yml
… and polish the maintenance workflow a bit.
Imho this is better for reviewers (and PR authors):
Before:
=> Run spec checks in their own GitHub Actions job

tests/test_appconfig.py, tests/test_codebuild.py, tests/test_dlm.py, troposphere/validators/appconfig.py, troposphere/validators/codebuild.py, troposphere/validators/dlm.py
Also fixed a broken `.join()` that I found while writing tests.
=> Fix valid values used by validators

tests/test_rds.py, troposphere/rds.py, troposphere/validators/rds.py
I run the `make regen` and commit the file. Not sure if it is needed or not.
=> Add validator for AWS::RDS::DBCluster.ServerlessV2ScalingConfiguration

troposphere/validators/rds.py
update validator for gp3 storage type, which isn't based on `Iops` minimum allocated storage anymore
=> Remove storage size validation for gp3 RDS StorageType

tests/test_ec2.py, troposphere/validators/ec2.py
Fixed #2155 compile error in ec2.py
Replace the build-in compile() function with re.compile(), and add test cases.
=> Fix compile error in ec2.py

troposphere/validators/rds.py
Troposphere has a new validator released in 4.3.1 that does not allow omitting the `Iops` attribute when gp3 and small StorageType parameters are passed. 
If we passed `Iops` to an instance under 400GB, with EngineType = mysql, postgres, mariadb; deploying CFN will provide the following deployment error:
```
2023-07-27T13:15:27.261000+00:00 CREATE_FAILED (AWS::RDS::DBInstance) testrds Resource handler returned message: "You can't specify IOPS or storage throughput for engine mysql and a storage size less than 400. (Service: Rds, Status Code: 400, Request ID: omitted)" (RequestToken: omitted, HandlerErrorCode: InvalidRequest)
2023-07-27T13:15:28.148000+00:00 CREATE_FAILED (AWS::IAM::Role) role Resource creation cancelled
2023-07-27T13:15:28.592000+00:00 ROLLBACK_IN_PROGRESS …
```
=> Update rds validator logic

troposphere/validators/cloudfront.py
"allExcept" is a valid behavior for the query_string/cookies/header config in AWS but is not allowed by the troposphere validators
Headers Config:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originrequestpolicy-headersconfig.html#cfn-cloudfront-originrequestpolicy-headersconfig-headerbehavior
Cookies Config:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originrequestpolicy-cookiesconfig.html#cfn-cloudfront-originrequestpolicy-cookiesconfig-cookiebehavior
Query Strings Config:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originrequestpolicy-querystringsconfig.html#cfn-cloudfront-originrequestpolicy-querystringsconfig-querystringbehavior
=> add all valid origin_request_policy config behaviors to validators

CONTRIBUTING.md, scripts/patches/events.py, troposphere/events.py
Per https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-tagging.html, only two EventBridge resources support tags:  event buses and rules.   The Troposphere EventBus resource had a field for tags, but Rules was missing it, probably because the Cloudformation Resource Specification was missing it.  This is issue https://github.com/cloudtools/troposphere/issues/2151.
This PR adds a jsonpatch to plug Tags for the Events::Rules resource into the resource specification and adds Tags to the Rules class. Also, the example for running `scripts/gen.py` included the cloudformation spec file as an argument, which causes gen.py to treat it as a service name and build a corrupted file.  This patch removes the cloudformation spec file from the example.
=> Added tags to EventBridge (Events) Rule resource and fixed an error in CONTRIBUTING.md

troposphere/serverless.py
Api Function Auth follows a different structure from Api Auth and thus should not re-use the same class.
Previously used https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html versus intended https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-apifunctionauth.html.
This PR fixes this discrepancy.
Fixes #2144
=> Add ApiFunctionAuth serverless class for Api Function events

troposphere/validators/iottwinmaker.py, troposphere/validators/wafv2.py
When the validator is used instead of the AWSProperty class (i.e. in WAFv2 for `Statement`), the TypeError() will return the expected AWSProperty SubClass as the last argument. This enables other libraries to identify the expected class and perform manipulations to import the resource property class.
For simpler class types (int, str, etc.) the validators only validate that the input is of that exact type and is simpler to catch.
Went over all the validators, these are the only two with an AWSProperty type validation, for due diligence. Although only need this today with WAFv2
=> TypeError() return the expected Class as last exception argument

troposphere/validators/rds.py
The new dbinstance validations do not check properties types resulting in testing a string `oracle` against `Ref` for example.
A lot of the tests should be ignored as soon as the DBClusterIdentifier is set, indicating that this is going to be an instance attached to Aurora DB Cluster.
Exception caught
```
File "/home/john/.cache/pypoetry/virtualenvs/ecs-composex-6XqxN9Zj-py3.9/lib/python3.9/site-packages/troposphere/validators/rds.py", line 401, in validate_dbinstance
and "oracle" in engine                                                                          
TypeError: argument of type 'Ref' is not iterable      
```
=> Fix RDS Validations

tests/test_basic.py, troposphere/__init__.py
Adds support to compare objects.
An advantage to using troposphere is being able to unit test various iterations of a dynamic template. However, the lack of support for being able to compare objects with one another makes these test cumbersome to write.
Resolves #1821
- added `.to_json()` method to base classes
- added `.__eq__()` and `.__ne__()` methods to base classes
- these use the newly added `.to_json()` method for comparison of same objects created from the same class to ensure properties are sorted in the same order
- comparing against a dict (or list for `AWSHelperFn` to support `Tags`) uses `.to_dict()` instead of converting both to a JSON string
- added `AWSHelperFn.__hash__()`
- `tests/test_tags.py:TestTags.test_Unsortable` was failing with `TypeError: unhashable type: 'Sub'` …
=> add support for object comparison

pyproject.toml, setup.cfg, troposphere/type_defs/compat.py
Python 3.7 reached its EOL on 2023-06-27, see https://peps.python.org/pep-0537/#lifespan
Python 3.7 was removed from the test matrix in commit bf8730b9a4307ee3e75f05d95c2ccdc23078a6ba.
=> Drop support for Python 3.7

tests/test_basic.py, tests/test_template.py, troposphere/__init__.py
Hello,
I'm maintaining a deployment tool based on troposphere and the latest update (4.5.0) failed one of my tests. This PR is supposed to fix the issue.
If it is not known how to compare objects, `__eq__` should return `NotImplemented` instead of `False`. That way the right side object of the comparison might possibly take over.
In my specific case the other object is a mock helper, which happily would do the comparison instead (and did until now).
Thank you.
=> Fix __eq__ protocol

tests/test_basic.py, troposphere/__init__.py
- Add __hash__ to the Parameter class
- Disable validation when doing BaseAWSObject object comparison __eq__
=> Object equality fixes

troposphere/validators/ec2.py
AssignIpv6AddressOnCreation depends on Ipv6CidrBlock, not the other way round.
=> Invert Ipv6CidrBlock Check

troposphere/validators/synthetics.py
The current Canary runtime versions are outdated. Under `troposphere/validators/synthetics.py` the valid versions are the following:
["syn-nodejs-2.0", "syn-nodejs-2.0-beta", "syn-1.0"]
The versions syn-nodejs-puppeteer-3.5 to syn-nodejs-puppeteer-3.9 were deprecated on January 8, 2024. ([Source](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library.html)) 
The current valid versions are the following:
* syn-nodejs-puppeteer-4.0
* syn-nodejs-puppeteer-5.0
* syn-nodejs-puppeteer-5.1
* syn-nodejs-puppeteer-6.0
* syn-nodejs-puppeteer-6.1
Let's add them to the valid canary runtime versions and replace the old ones.
=> Fix valid canary runtime versions

tests/test_rds.py, troposphere/validators/rds.py
Fixes #2176
The [test case](https://github.com/cloudtools/troposphere/issues/2176#issuecomment-1940482962) in the Issue was [falling through](https://github.com/cloudtools/troposphere/issues/2176#issuecomment-1938252769) to the body of the if statement which was an indication the test was incorrect.
@tnielsen2 @JohnPreston @uldall looking for a quick code review if you have time to check it
=> Fix RDS validator for gp3 iops/allocated_storage ratio check

troposphere/validators/synthetics.py
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html#CloudWatch_Synthetics_runtimeversion-nodejs-puppeteer-6.2
=> Add syn-nodejs-puppeteer-6.2 as valid canary runtime

troposphere/validators/synthetics.py
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Library_nodejs_puppeteer.html#CloudWatch_Synthetics_runtimeversion-nodejs-puppeteer-7.0
=> Add syn-nodejs-puppeteer-7.0 as valid canary runtime

troposphere/validators/dlm.py
Add `1` as valid interval for DLM rule.  This fixes #2237.
=> Update DLM Interval value

troposphere/serverless.py
AWS docs/ref:
* https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-kinesis.html#sam-function-kinesis-filtercriteria
fixes error:
* AttributeError: Kinesis object does not support attribute FilterCriteria
```python
Function(
title='MyLambdaFunction',
Events={
"KinesisEvent": KinesisEvent(
title="KinesisEvent",
Stream='arn:aws:kinesis:us-east-1:123456789012:stream/my-stream',
StartingPosition=TRIM_HORIZON,
FilterCriteria=FilterCriteria(  # this change allows to add filters
Filters=[
Filter(Pattern='{"key": ["val1", "val2"]}'),
]
),
)
}
)
```
=> add FilterCriteria to serverless/KinesisEvent

troposphere/serverless.py
AWS docs/ref:
* https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-mq.html#sam-function-mq-sourceaccessconfigurations
fixes error:
* TypeError: <class 'troposphere.serverless.MQEvent'>: MQEvent.SourceAccessConfigurations is <class 'troposphere.awslambda.SourceAccessConfiguration'>, expected [<class 'str'>]
```python
Function(
title='MyLambdaFunction',
Events={
"MQEvent": MQEvent(
title="MQEvent",
Broker='arn:aws:mq:us-east-2:123456789012:broker:MyBroker:b-1234a5b6-78cd-901e-2fgh-3i45j6k178l9',
Queues=['my-queue'],
SourceAccessConfigurations=[  # now it's array of [SourceAccessConfiguration]
SourceAccessConfiguration(
Type="BASIC_AUTH",
URI='arn:aws:secretsmanager:us-east-1:01234567890:secret:MyBrokerSecretName',
), …
```
=> fix serverless/MQEvent SourceAccessConfigurations property type

troposphere/validators/codebuild.py
GitLab is [now supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-source.html#cfn-codebuild-project-source-type) as a source for CodeBuild projects.
=> Add support for GitLab sources in CodeBuild projects

troposphere/validators/glue.py
The SNOWFLAKE validation type allows an AWS::Glue::Connection with the ConnectionType of `SNOWFLAKE` to be created.
This is not yet in any documentation nor is the underlying API documented :( 
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1810
=> Update glue.py with SNOWFLAKE validate type

troposphere/validators/ssm.py
OperatingSystem accept AMAZON_LINUX_2023 and AMAZON_LINUX_2022
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html#cfn-ssm-patchbaseline-operatingsystem
=> Adding two new values to OperatingSystem attributes

troposphere/validators/apigateway.py, troposphere/validators/apigatewayv2.py
Setting upper limit of integration timeout to max timeout time for a lambda function. This is per the change AWS has rolled out which allows the integration timeout to be increased beyond 29000: https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-api-gateway-integration-timeout-limit-29-seconds/
=> APIGW Integration Timeout Increase

troposphere/constants.py
Pulled the cache instance types with `aws elasticache describe-reserved-cache-nodes-offerings` and updated the constants.py file per #2261
@javid-abd could you review?
=> Update ElastiCache instance types

tests/test_serverless.py, tests/test_tags.py, troposphere/__init__.py
Prior to this change Tags (which is a subclass of AWSHelperFn) would not do validation of the expected type and it prevented validation of Json style Tags needing a dict.
Fixes #2268
=> Validate the type for Tags

tests/test_tags.py, troposphere/__init__.py
Instead of checking the property name, we check the type of the value. This means that the Tags class gets checked, but other helper functions are allowed
We were running into this issue, because we have a custom resource that outputs a tag list.
I've also added tests for this case
=> Allow AWSHelperFn for Tags properties

troposphere/validators/elasticsearch.py
it's not listed in [CloudFormation doc ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-domainendpointoptions.html#cfn-elasticsearch-domain-domainendpointoptions-tlssecuritypolicy), but it's mentioned [here](https://docs.aws.amazon.com/securityhub/latest/userguide/es-controls.html#es-8) and I tested that it actually works
=> Add "Policy-Min-TLS-1-2-PFS-2023-10" as valid value TlsSecurityPolicy

troposphere/validators/kinesisanalyticsv2.py
AWS has added support for Apache Flink 1.20 in Kinesis Data Analytics. This PR updates the VALID_RUNTIME_ENVIRONMENTS tuple in troposphere/validators/kinesisanalyticsv2.py to include "FLINK-1_20".
This ensures Troposphere users can define applications using the latest supported Flink runtime without encountering validation errors.
Change Summary:
Added "FLINK-1_20" to the list of valid runtime environments
Reference:
Issue: https://github.com/cloudtools/troposphere/issues/2299
[AWS Announcement for Flink 1.20 Support](https://docs.aws.amazon.com/managed-flink/latest/java/flink-1-20.html)
=> [2299] Add support for FLINK-1_20 in validate_runtime_environment

tests/test_template_generator.py, troposphere/template_generator.py
The template generator would introduce a list wrapping for AWS Functions (Cidr, GetAZs, Split) that return a list resulting in the function results wrapped in a list. This detects and corrects that behavior.
@ilons I expanded the scope of your patch to include other functions and added a test. Could you review, test, and approve?
Fixes #2162
=> Handle AWS list functions in template generator

troposphere/validators/rds.py
This is a new PR addressing comments from #2334 and should "fix" Issue #2333
Sorry for closing the old one and open a new ... but I wasn't able to fully do all operations on my work account, so I moved to my personal one.
=> Add new oracle-ee-cdb engine to the valid db engine on rds validator
