- CHANGELOG.md
- examples/DynamoDB_Table.py
- examples/DynamoDB_Table_With_GlobalSecondaryIndex.py
- tests/examples_output/DynamoDB_Table.template
- tests/examples_output/DynamoDB_Table_With_GlobalSecondaryIndex.template
- troposphere/dynamodb.py
Fixes PEP8 issues and updates examples_output info
There may be a better way to do this with github, but I'm not aware of it :)
> Updated GH-161

- troposphere/cloudwatch.py
> GH-159: Changing CloudWatch Alarm's Threshold prop to be basestring

- examples/RedshiftClusterInVpc.py
- tests/examples_output/RedshiftClusterInVpc.template
> Fixing RedshiftClusterInVpc example; incorrect SG setup

- examples/CloudFront_S3.py
- tests/examples_output/CloudFront_S3.template
- troposphere/cloudfront.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-cachebehavior.html#cfn-cloudfront-cachebehavior-forwardedvalues
> forwarded values required on cache behavior

- troposphere/dynamodb.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-attributedef
> attribute definitions required

- examples/ELBSample.py
- tests/examples_output/ELBSample.template
Updating issue: https://github.com/cloudtools/troposphere/issues/199
> Updating AMI IDs for other Regions. Adding CFN template metadata.

- troposphere/logs.py
Cloudformation expects a string as a FilterPatter
> Cloudformation expects a string as a FilterPatter

- README.rst
Mostly this is to clean up the ugliness that results in using markdown on pypi.
> Readme in rst

- troposphere/elasticache.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#cfn-elasticache-cachecluster-numcachenodes
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-security-group.html#cfn-elasticache-securitygroup-description
> required elasticache properties

- troposphere/constants.py
- troposphere/rds.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-eventsubscription.html
> EventSubscription resource + EC2 types

- troposphere/opsworks.py
I couldn't find any good examples that use these things to copy for tests.  The only part I'm not 100% happy with is the 'float' properties in AutoScalingThresholds.  Those are listed as 'Number' in the docs:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opsworks-layer-loadbasedautoscaling-autoscalingthresholds.html
Wasn't sure how to validate either a float or int.
> Add 2015-04-16 OpsWork changes

- tests/test_validators.py
- troposphere/s3.py
- troposphere/validators.py
Added a validator for s3 bucket names to get past the basestring (alphanumeric) limitation.  Used a regex to handle that.
Also... added a validator test for the new s3_bucket_name validator.
> add true s3 bucket name validator

- troposphere/constants.py
> Add M4 instances and Memcached port

- examples/ClassExtensions.py
- tests/examples_output/ClassExtensions.template
- troposphere/__init__.py
fixes #233
this should allow one to use class hierarchies to remove redundant
definition of properties in similar resources
> allow extending classes + tests

- troposphere/constants.py
https://aws.amazon.com/about-aws/whats-new/2015/06/introducing-a-new-amazon-ec2-t2-instance-t2-large/
> adding t2 large

- examples/IAM_Users_Groups_and_Policies.py
- tests/examples_output/IAM_Users_Groups_and_Policies.template
- tests/test_validators.py
- troposphere/iam.py
- troposphere/validators.py
*status is required http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iam-accesskey.html
* tests for validators
*adding managedPolicyArns
> status required and managedpolicyarns

- scripts/cfn2py
- tests/test_dict.py
- troposphere/__init__.py
adds feature discussed in #293
> adds from_dict function to BaseAWSObject allowing for objects to be created from data structures

- tests/test_basic.py
- troposphere/__init__.py
See:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
> Validate parameter options based on Type

- tests/test_rds.py
- troposphere/rds.py
This matches all the new gotchas in:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-storagetype
> Add more specific validators to DBInstance

- troposphere/constants.py
This includes all the parameter types from http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
> Add constants for the parameter types

- troposphere/__init__.py
This lets you figure out what resource you were working on when the
issue popped up.
> Gives more info about type errors

- troposphere/rds.py
First pass at adding/changing what is there to bring up an Aurora cluster.
> Add support for Aurora

- troposphere/codedeploy.py
> change definition to list to match cloudformation

- troposphere/autoscaling.py
- troposphere/cloudfront.py
- troposphere/directoryservice.py
- troposphere/logs.py
- troposphere/s3.py
- troposphere/waf.py
This should help with issue #365.
> Various updates from Dec 3 & 28 2015 releases

- troposphere/rds.py
Add mariadb to list of available RDS engines
> Add mariadb to list of RDS engines

- troposphere/constants.py
> Adding ap-northeast

- troposphere/constants.py
Added the new(ish) T2 nano instance.
> Adding T2 nano

- scripts/cfn
Allow to pass ``--capability CAPABILITY_IAM`` argument.
c.f.: http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStack.html
> Capabilities

- examples/NatGateway.py
- tests/examples_output/NatGateway.template
- troposphere/ec2.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-natgateway.html
cc @martinb3
> Added EC2 Nat Gateway resource

- README.rst
- setup.py
`pip install troposphere[policy]` will install troposphere + awacs
> recommended soft dependency

- troposphere/__init__.py
Not sure how best to test this - open to any suggestions.  Also not a
huge fan of the way I'm giving the info, but can't think of a better way
without breaking any previous use that already handled errors in a
particular way.
> Give more info on func validator failures

- troposphere/ecr.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html
> AWS::ECR::Repository

- README.rst
- examples/ECRSample.py
- tests/examples_output/ECRSample.template
@phobologic as promised
ref: https://github.com/cloudtools/troposphere/pull/395
> AWS::ECR test example

- README.rst
- examples/ElasticsearchDomain.py
- tests/examples_output/ElasticsearchDomain.template
- troposphere/elasticsearch.py
Implemented AWS::Elasticsearch resource creation.
Fixes #411
> Elasticsearch support

- troposphere/awslambda.py
> Allow both GetAtt and a basestring.

- troposphere/autoscaling.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-policy.html#cfn-as-scalingpolicy-scalingadjustment
> ScalingAdjustment is an integer

- troposphere/awslambda.py
Sorry for the previous pull request fiasco. This should be a bit smoother :)
> Add FunctionName to Lambda::Function #450

- examples/EMR_Cluster.py
- tests/examples_output/EMR_Cluster.template
- troposphere/emr.py
This PR addresses my last comment in issue #412
> Add support for EBS Volumes in EMR resources

- examples/IAM_Users_Groups_and_Policies.py
- tests/examples_output/IAM_Users_Groups_and_Policies.template
Updated IAM_Users_Groups_and_Policies.py example to make it work out of the box.
> move Groups to property, add policy template version

- troposphere/template_generator.py
The template generator's fallback try/catch was a bit too focused; it should always be used as a last resort.
This fixes the "Tags" case where args is a mapping and gets called with a single *unpacking star.
> Better AWSHelperFn support in template generator

- examples/ApiGateway.py
- tests/examples_output/ApiGateway.template
- troposphere/apigateway.py
> fix attribute for ApiKey (Enable -> Enabled)

- troposphere/dynamodb2.py
This is python, not javascript 😉
> Invoke join correctly

- README.rst
- examples/Firehose_with_Redshift.py
- tests/examples_output/Firehose_with_Redshift.template
- troposphere/firehose.py
- https://aws.amazon.com/about-aws/whats-new/2016/06/aws-cloudformation-adds-support-for-amazon-vpc-flow-logs-amazon-kinesis-firehose-streams-and-other-updates/
- http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisfirehose-deliverystream.html
> added support for Kinesis Firehose

- troposphere/kinesis.py
https://aws.amazon.com/about-aws/whats-new/2016/06/aws-cloudformation-adds-support-for-amazon-vpc-flow-logs-amazon-kinesis-firehose-streams-and-other-updates/
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html
> Added Name property to Kinesis streams

- tests/test_rds.py
- troposphere/rds.py
> Allows MultiAZ=false with AvailabilityZone in rds

- troposphere/awslambda.py
> Remove double S from S3ObjectVersion (fixes #530)

- examples/CertificateManagerSample.py
- tests/examples_output/CertificateManagerSample.template
- troposphere/certificatemanager.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-certificatemanager-certificate.html
> AWS Certificate Manager

- examples/ApplicationAutoScalingSample.py
- tests/examples_output/ApplicationAutoScalingSample.template
- troposphere/applicationautoscaling.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalingpolicy.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalabletarget.html
> Add Application Auto Scaling

- troposphere/efs.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
> EFS updates (Aug 9, 2016)

- examples/IoTSample.py
- tests/examples_output/IoTSample.template
- troposphere/iot.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-topicrule.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-thingprincipalattachment.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-thing.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-policyprincipalattachment.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-policy.html
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-certificate.html
> AWS Internet of Things

- troposphere/ecs.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-loadbalancers.html
> Update ECS LoadBalancer property

- tests/test_policies.py
- troposphere/policies.py
> Add support for AutoScalingCreationPolicy

- examples/ECSCluster.py
- tests/examples_output/ECSCluster.template
In response to #554 I'm adding an example of an ECS Cluster with a few attached policies
> adding a sample ECS Cluster template

- troposphere/kinesis.py
Kinesis Stream is missing the Tags property.
This seems a little too easy, let me know if there's something I'm missing.
> add Tags prop

- troposphere/__init__.py
Tested from the code I've been using for the last couple of weeks
> Added cross-stack references

- tests/test_basic.py
- troposphere/__init__.py
- issue cloudtools/troposphere#577
> add support for `Fn::Sub`

- troposphere/__init__.py
Update Export param to use Export(string) instead of dict
> Update Export param

- troposphere/ec2.py
This pull request resolves issue #595 by adding a Placement class and using this in the LaunchSpecifications property.
> Added Placement class for the Placement property in LaunchSpecifications.

- examples/Redshift.py
- tests/examples_output/Redshift.template
> Fix typo in Example Allowed Values

- tests/test_parameters.py
- tests/test_template.py
- troposphere/__init__.py
Added validation for parameters, and for reaching max resources on a template. Fixes #634
> Extra validation

- troposphere/ecs.py
https://aws.amazon.com/about-aws/whats-new/2017/01/aws-cloudformation-introduces-support-for-listing-imports-split-function-and-resource-coverage-updates/
> Update ECS to Jan 17, 2017 release

- troposphere/rds.py
https://aws.amazon.com/about-aws/whats-new/2017/01/aws-cloudformation-introduces-support-for-listing-imports-split-function-and-resource-coverage-updates/
> Update RDS to Jan 17, 2017 release

- tests/test_asg.py
- tests/test_policies.py
- troposphere/autoscaling.py
Fixes #653
Also updated some test names to make them more explicit.
> Allow HelperFN w/ autoscaling policies

- tests/test_stepfunctions.py
- troposphere/stepfunctions.py
Added the basic step function resources.
> Added step functions and basic tests

- examples/CloudTrail.py
- tests/examples_output/CloudTrail.template
Adding an example for CloudTrail.
I converted the official example from the [doc](http://docs.aws.amazon.com/AWSClo…udFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html)
It's been requested in https://github.com/cloudtools/troposphere/issues/314
> Adding example for CloudTrail

- examples/ApiGateway.py
- tests/examples_output/ApiGateway.template
I have corrected ApiGateway sample code so the stack is being created correctly now (original one raises errors during creation).
> Fix ApiGateway.py sample

- troposphere/sqs.py
Adding new SQS properties.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html
> SQS: Add FifoQueue and ContentBasedDeduplication

- examples/S3_Bucket_With_Versioning_And_Lifecycle_Rules.py
Fix typo in S3_Bucket_With_Versioning_And_Lifecycle_Rules.py :)
> Fix typo in S3_Bucket_With_Versioning_And_Lifecycle_Rules.py

- troposphere/elasticloadbalancingv2.py
This was announced in:
https://aws.amazon.com/about-aws/whats-new/2017/04/aws-cloudformation-adds-support-for-amazon-cognito-ebs-elastic-volumes-and-updates-resource-coverage/
> Add IpAddressType property to elbv2.

- examples/S3_Bucket.py
- tests/examples_output/S3_Bucket.template
Changed EC2 instance to S3 Bucket in description
> Fix typo in S3_Bucket.py example

- troposphere/__init__.py
This can help with typos, and the pseudo parameters are really only used
in this way.
> Add Pseudo Parameter Ref objects

- examples/EMR_Cluster.py
- tests/examples_output/EMR_Cluster.template
- tests/test_emr.py
- troposphere/emr.py
> Introduces AWS::EMR::SecurityConfiguration Support for Troposphere

- examples/ApiGateway.py
- tests/examples_output/ApiGateway.template
Tried the example, it failed before.  This fixes it so it will actually complete
> Fixed UsagePlan example to proper Ref

- tests/test_basic.py
- troposphere/__init__.py
> Raise TypeError when a scaler AWSHelperFn is used in a list context

- examples/SQSEncrypt.py
- tests/examples_output/SQSEncrypt.template
- troposphere/sqs.py
Based on https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-kmsmasterkeyid
Tested new example and SQS queue is created with the specified encryption key.
> adding sqs server side encryption

- examples/CodeDeploy.py
- tests/examples_output/CodeDeploy.template
- troposphere/codedeploy.py
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html
> Support new code deploy options

- examples/RedshiftClusterInVpc.py
- tests/examples_output/RedshiftClusterInVpc.template
Changes `multi-mode` to `multi-node`.
> Fixes spelling error.

- troposphere/elasticloadbalancingv2.py
Add AvailabilityZone to AWS::ElasticLoadBalancingV2::TargetGroup #829
> Add AvailabilityZone property to TargetDescription

- troposphere/events.py
see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-ecsparameters.html
> Add `Event::Rule::Target::EcsParameters`

- troposphere/events.py
Add missing  `AWS::Events::Rule` Target properties:
* `InputTransformer`
* `KinesisParameters`
* `RunCommandParameters`
> Events target (fixes #830)

- troposphere/elasticbeanstalk.py
> Added platformArn to Environment and ConfigurationTemplate

- tests/s3.py
- tests/test_basic.py
- troposphere/s3.py
> Refactor s3.Bucket to remove custom __init__() and add tests

- troposphere/autoscaling.py
- troposphere/certificatemanager.py
- troposphere/cloudformation.py
- troposphere/ec2.py
- troposphere/elasticloadbalancing.py
- troposphere/elasticloadbalancingv2.py
- troposphere/elasticsearch.py
- troposphere/emr.py
- troposphere/kinesis.py
- troposphere/rds.py
> Be more explicit on the use of the Tags object for Tags

- troposphere/ssm.py
added MaintenanceWindow for SSM.
> add maintenance window for SSM

- README.rst
- troposphere/glue.py
These were introduced on [October 24, 2017](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html).
Takes care of https://github.com/cloudtools/troposphere/issues/870.
> Adding the various Glue resources

- troposphere/ec2.py
- troposphere/validators.py
Support for VpnTunnelOptionsSpecifications allows specification of PreSharedKey and TunnelInsideCidr.
> Added support for VpnTunnelOptionsSpecifications

- examples/ElasticsearchDomain.py
- tests/examples_output/ElasticsearchDomain.template
- troposphere/elasticsearch.py
Hello :)
I'm trying to solve this issue I opened some minutes ago https://github.com/cloudtools/troposphere/issues/861
The idea is to add support for VPCOptions in ElasticSearch (you will find more info in the issue).
Hope this works!
> Add support for VPCOptions in ElasticSearch

- troposphere/ecr.py
These are the minor code changes I've had to make in order to fix the problem I reported on https://github.com/cloudtools/troposphere/issues/953
> Fixes the lifecyclepolicy problem reported at Issue #953

- troposphere/openstack/nova.py
Hi,
I found that Server object doesn't have this property so maybe it's a good idead to add it.
> Adding support for Block Device Mapping V2

- troposphere/apigateway.py
Fixes https://github.com/cloudtools/troposphere/issues/949
> Correct type in response type

- docs/README.md
It seems like it's not very clear at first sight how Troposphere should be used, people are looking for docs (ex. #650). I did too. This is an attempt to maybe get people starting. It's a README.md file in 'docs' directory, which means that http://troposphere.readthedocs.io/en/latest/ should pick it up, if I understand correctly.
Do you think it would be useful?
> Stab at documenting Troposphere basics

- tests/test_serverless.py
- troposphere/serverless.py
Changed policy_validator function to allow for an IAM Policy Document value for Policies attribute.
> Add support for Policy Document in SAM template.

- troposphere/ecs.py
https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ecs-adds-elb-health-check-grace-period/
> Adding HealthCheckGracePeriodSeconds into ECS Service

- troposphere/ssm.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html#cfn-ssm-parameter-allowedpattern
> Add AllowedPattern to Parameter

- troposphere/validators.py
SUSE is a supported operating system for SSM. 
See BOTO3 docs:
http://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.create_patch_baseline
> Adding SUSE to list of operating systems

- troposphere/guardduty.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-guardduty-member.html#cfn-guardduty-member-disableemailnotification
> Add `DisableEmailNotification` to `AWS::GuardDuty::Member`

- examples/NatGateway.py
- tests/examples_output/NatGateway.template
Nat gateway is a different resource from a Nat instance. I have updated the description to reflect the same as per my understanding.
> Corrected the description of NatGateway

- troposphere/autoscaling.py
- troposphere/config.py
- troposphere/ec2.py
Added Launch Templates now that CFN supports them
> Adding Launch Templates

- troposphere/ec2.py
- troposphere/validators.py
- update VPCEndpoint to support new properties in Cloudformation
- add AWS::EC2::VPCEndpointService
> AWS PrivateLink support

- troposphere/serverless.py
* Adds SQS event type to serverless application model
> Add SQS Event

- troposphere/iam.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html#cfn-iam-servicelinkedrole-awsservicename
> Add AWS::IAM::ServiceLinkedRole

- troposphere/serverless.py
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlesssimpletable
> SimpleTable has more attributes

- troposphere/config.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-configurationaggregator.html#cfn-config-configurationaggregator-accountaggregationsources
> AccountAggregationSources must be a list

- troposphere/sns.py
As per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html
> Add FilterPolicy as a property of SubscriptionResource

- troposphere/ec2.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservicepermissions.html
> Add AWS::EC2::VPCEndpointServicePermissions (#1128)

- troposphere/apigateway.py
Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration.html#cfn-apigateway-method-integration-connectionid
> Added ConnectionId and ConnectionType to API GW method integration

- tests/test_template.py
- troposphere/__init__.py
> Add support for AWS-interface metadata

- tests/test_ecs.py
- troposphere/ecs.py
> [#1167] Add support for DockerVolumeConfiguration in AWS::ECS::TaskDefinition

- troposphere/codebuild.py
> Add missing Codebuild source types

- tests/test_rds.py
- troposphere/rds.py
Adds support for EngineMode and ScalingConfiguration properties in RDS DBCluster
Closes #1155
> [#1155] Aurora serverless support

- troposphere/apigateway.py
[AWS CloudFormation Release History](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
> Update apigateway as of 09/20/18

- troposphere/codebuild.py
[AWS CloudFormation Release History](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
> Update codebuild as of 09/20/18

- troposphere/codedeploy.py
[AWS CloudFormation Release History](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
> Update codedeploy as of 09/20/18

- troposphere/route53.py
Add MultiValueAnswer for AWS::Route53::RecordSet
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html?shortFooter=true#cfn-route53-recordset-multivalueanswer
> Add MultiValueAnswer property for AWS::Route53::RecordSet

- troposphere/iam.py
> Adds Permissions Boundaries on AWS::IAM::Role and AWS::IAM::User

- tests/test_awslambda.py
- troposphere/awslambda.py
> Validate Lambda environment variable names

- troposphere/sagemaker.py
Fix breaking bugs in sagemaker, add missing properties.
> Fix bugs and add missing properties in sagemaker

- troposphere/appsync.py
> adding new appsync FunctionConfiguration resource & properties, per Nov 20 2018 update

- troposphere/config.py
Documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-config-configurationaggregator-organizationaggregationsource.html
> Correct RoleArn case for OrganizationAggregationSource

- examples/CloudFront_S3.py
- tests/examples_output/CloudFront_S3.template
- troposphere/cloudfront.py
- troposphere/validators.py
`cloudfront.py`
`validators.py`
`examples/CloudFront_S3.py`
`tests/examples_output/CloudFront_S3.template`
Adds missing parameters
Fixes incorrect `Origin` specification
Adds validators
Fixes #978
> Updates CloudFront with missing parameters and validators

- examples/Batch.py
- tests/examples_output/Batch.template
- troposphere/batch.py
This PR adds support for AWS Batch PlacementGroup & LaunchTemplate options
For more details, see [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html)
> Added support for AWS Batch PlacementGroup & LaunchTemplate

- README.rst
This PR changes the build badges to SVG for sharper readability ✨
> README.rst: Use SVG build status badge

- examples/SSMExample.py
- tests/examples_output/SSMExample.template
This change will aim to add an example for SSM and it's patch baseline/filter capabilities.  Currently there isn't a template for this so adding this for future reference incase anyone needs to use this feature within Cloudformation.
> SSM Example.

- troposphere/dynamodb.py
Updates the validator to ignore helper functions that do not have properties. 
Fixes #1279 
`dynamodb.py`
> Fixes DynamoDB validator error.

- tests/test_tags.py
- troposphere/__init__.py
> fix tag sorting on py3

- troposphere/apigateway.py
closes issue https://github.com/cloudtools/troposphere/issues/1315
> fix accesslogsetting prop

- troposphere/codebuild.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projectcache.html#cfn-codebuild-project-projectcache-modes
> Add new Codebuild property

- troposphere/apigateway.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html#cfn-apigateway-apikey-value
> Add new Apikey property

- troposphere/elasticsearch.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html#cfn-elasticsearch-domain-nodetonodeencryptionoptions
> Add new Elasticsearch Domain property

- troposphere/rds.py
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-usedefaultprocessorfeatures
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-sourceregion
> Add new RDS DBCluster and DBInstance properties

- troposphere/autoscaling.py
Add missing Termination Policies for ASG.
> add missing Termination Policies

- scripts/cfn
- scripts/cfn2py
- scripts/gen.py
Running the scripts through pylint gives a lot of errors...  It seems like these scripts are out of date and need a little TLC...
This is just a basic patch to get the code working in Python3, though I'm not sure if the basestring hack is the best approach below.
> Fix the scripts for Python3

- troposphere/ec2.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-capacityreservation.html
> Add AWS::EC2::CapacityReservation resource

- troposphere/ecs.py
- troposphere/validators.py
Also added other new parameters such as: ProxyConfiguration for TaskDefinition and  DependsOn, StartTimeout and StopTimeout for ContainerDefinition.
> Added ECS ProxyConfiguration, DependsOn,  StartTimeout and StopTimeout parameters

- troposphere/constants.py
`ap-northeast-2` (Seoul) has only 2 AZs, see https://aws.amazon.com/about-aws/global-infrastructure/regions_az/ and `aws ec2 describe-availability-zones --region 'ap-northeast-2'`
> Update region/az information

- troposphere/wafregional.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-geomatchset.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-ratebasedrule.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafregional-regexpatternset.html
> Add new wafregional resources

- troposphere/elasticloadbalancingv2.py
Add de HttpHeaderConfig support for ALB ListenerRule
> Add support for httpHeaderConfig

- troposphere/ecs.py
- Add Tags to ECS Cluster, Service and TaskDefinition
- Add Secret and ResourceRequirements to ContainerDefinition
- Fix optional properties
> Update ECS resources from June 13, 2019 update

- troposphere/ec2.py
Per docs here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html
> Add transit gateway ID to Route

- troposphere/dlm.py
See updated documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dlm-lifecyclepolicy-createrule.html#cfn-dlm-lifecyclepolicy-createrule-interval
> Update DLM rule interval values (#1333)

- troposphere/codecommit.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codecommit-repository-code.html
> Codecommit Code Property Support

- troposphere/ec2.py
Pull Request for features implementation of https://github.com/cloudtools/troposphere/issues/1457
> Add support for LicenseSpecification for LaunchTemplateData

- troposphere/cloudwatch.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-anomalydetector.html
> Add Cloudwatch AnomalyDetector resource

- troposphere/dms.py
https://github.com/cloudtools/troposphere/issues/1463
> Adding AllowMajorVersionUpgrade to DMS Replication Instance

- troposphere/elasticache.py
A possible fix for issue #1465. Thanks
> Change ReplicaAvailabilityZones from string type to string list

- troposphere/kinesisanalyticsv2.py
A fix for the issue: https://github.com/cloudtools/troposphere/issues/1471
> Issue #1471: fix bug in CodeContent object

- troposphere/ssm.py
Add new properties to class MaintenanceWindow:
EndDate,
ScheduleTimezone,
StartDate,
Tags
> feat: Update MaintenanceWindow Properties

- troposphere/ssm.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-parameter.html
> Add new Properties to SSM::Parameter

- README.rst
This PR adds hyperlinks to official AWS resource types documentation for all of the supported AWS resource types.
✅ Verified all hyperlinks
> Add hyperlinks to AWS resource types in README

- troposphere/batch.py
Adding new parameter for AWS::Batch::ComputeEnvironment ComputeResources. The full description is here https://aws.amazon.com/blogs/compute/optimizing-for-cost-availability-and-throughput-by-selecting-your-aws-batch-allocation-strategy/
> Add AllocationStrategy parameter for AWS::Batch::ComputeEnvironment ComputeResources

- troposphere/events.py
This adds the EventBus resource.
> Add EventBus class in events script

- tests/test_validators.py
- troposphere/validators.py
- troposphere/waf.py
- troposphere/wafregional.py
Adding the WAS Action Type validator for WAF and WAFRegional.
> Add WAF Action Type validator

- troposphere/ec2.py
https://github.com/cloudtools/troposphere/issues/1530
> Adding CpuOptions support for LaunchTemplateData

- troposphere/awslambda.py
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-alias.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-version.html
> Add ProvisionedConcurrencyConfiguration for Lambda alias and version

- README.rst
- troposphere/wafv2.py
This PR is quite big and the number of imbricated resources is mind boggling, so any review is appreciated.
> adding WAFv2 resources, per Nov 25 2019 update

- troposphere/rds.py
https://github.com/cloudtools/troposphere/issues/1572
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-enginemode
> expanding AWS::RDS::DBCluster VALID_DB_ENGINE_MODES

- troposphere/eks.py
Fix a couple of types in the NodeGroup, per https://github.com/cloudtools/troposphere/issues/1574
> Nodegroup tags type

- troposphere/ec2.py
waiting for `PartitionNumber` and `HostResourceGroupArn` to land in the `AWS::EC2::LaunchTemplate` documentation.
> Adding misc EC2 properties, per Feb 6 2020 update

- troposphere/kinesisanalyticsv2.py
fixes https://github.com/cloudtools/troposphere/issues/1583
> AWS::KinesisAnalyticsV2::Application.RuntimeEnvironment VALID_RUNTIME_ENVIRONMENTS

- troposphere/lakeformation.py
> adding misc Lakeformation properties, per Jan 16 2020 update

- troposphere/wafv2.py
> fixing property according to the documentation's example

- README.rst
- troposphere/resourcegroups.py
- troposphere/validators.py
> Adding AWS::ResourceGroups::Group resource, per March 19, 2020 update

- troposphere/ec2.py
> adding AWS::EC2::ClientVpnEndpoint properties, per March 19, 2020 update

- troposphere/dms.py
> Adding AWS::DMS::Endpoint props, per March 23, 2020 update

- troposphere/autoscaling.py
> Adding AWS::AutoScaling::AutoScalingGroup props, per March 26, 2020 update

- troposphere/apigatewayv2.py
> Adding misc AWS::ApiGatewayV2::Integration properties, per March 26, 2020 update

- troposphere/cloudwatch.py
> Adding AWS::CloudWatch::InsightRule props, per April 2, 2020 update

- troposphere/serverless.py
As per this document: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-schedule.html
> Update SAM Schedule event source spec

- README.rst
- troposphere/detective.py
> Adding AWS::Detective resources, per March 26, 2020 update

- troposphere/apigatewayv2.py
> Adding missing AWS::ApiGatewayV2::VpcLink object

- troposphere/codestarconnections.py
> Add AWS::CodeStarConnections::Connection props, per May 14, 2020 update

- troposphere/dms.py
> Adding misc AWS::DMS properties, per May 14, 2020 update

- troposphere/mediastore.py
- troposphere/validators.py
> Adding misc AWS::MediaStore::Container properties, per May 14, 2020 update

- troposphere/servicecatalog.py
> updating AWS::ServiceCatalog::CloudFormationProduct properties, per May 14, 2020 update

- troposphere/synthetics.py
> Changing AWS::Synthetics::Canary props, per May 14, 2020 update

- troposphere/imagebuilder.py
> Fixing misc AWS::ImageBuilder properties

- troposphere/ssm.py
> Update AWS::SSM::Parameter properties, per May 21, 2020 update

- troposphere/codebuild.py
> Update AWS::CodeBuild::ReportGroup properties, per May 21, 2020 update

- troposphere/ec2.py
Adding hibernation options to LaunchTemplateData
> Adding hibernation options to LaunchTemplateData

- troposphere/awslambda.py
Add OnSuccess for DestinationConfig.
> add OnSuccess

- troposphere/dms.py
https://github.com/cloudtools/troposphere/issues/1732
> This isn't required

- troposphere/sagemaker.py
> Support attribute Mode for SageMaker Model ContainerDefinition

- examples/CloudTrail.py
- tests/test_validators.py
> Make flake8 happy again

- troposphere/docdb.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-deletionprotection
> AWS::DocDB::DBCluster.DeletionProtection

- tests/test_serverless.py
- troposphere/serverless.py
See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-domain
> Add AWS::Serverless::Api's Domain

- tests/test_efs.py
- troposphere/efs.py
fixes https://github.com/cloudtools/troposphere/issues/1754
> AWS::EFS::FileSystem.BackupPolicy

- examples/SSMExample.py
- tests/examples_output/SSMExample.template
SSM Parameter usage examples with values that has inline python function from a standard-library.
> Added SSM Parameter examples

- troposphere/stepfunctions.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-stepfunctions-statemachine.html#cfn-stepfunctions-statemachine-tracingconfiguration
> AWS::StepFunctions::StateMachine.TracingConfiguration

- .travis.yml
- setup.py
3.9.0 final is [expected](https://www.python.org/dev/peps/pep-0596/#schedule) on Monday, 2020-10-05.
> Run tests against Python 3.9

- troposphere/msk.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-msk-cluster-clientauthentication.html
> AWS::MSK::Cluster.ClientAuthentication.Sasl

- troposphere/cloudwatch.py
Add period to CloudWatch::Alarm MetricDataQuery
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-alarm-metricdataquery.html
> Added Period attribute to CloudWatch::Alarm MetricDataQuery

- troposphere/constants.py
https://docs.aws.amazon.com/general/latest/gr/rande-manage.html
https://aws.amazon.com/blogs/aws/category/regions/
https://aws.amazon.com/blogs/aws/now-open-aws-middle-east-bahrain/
https://aws.amazon.com/about-aws/whats-new/2019/05/aws-asia-mumbai-adds-third-availability-zone/
https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/helpers.py
```bash
$ aws ec2 describe-regions | pcregrep -o1 '"RegionName": "(.*)"' | xargs -L1 bash -c 'aws ec2 describe-availability-zones --region $0 | grep "ZoneName"'
"ZoneName": "eu-north-1a",
"ZoneName": "eu-north-1b",
"ZoneName": "eu-north-1c",
"ZoneName": "ap-south-1a",
"ZoneName": "ap-south-1b",
"ZoneName": "ap-south-1c",
"ZoneName": "eu-west-3a",
"ZoneName": "eu-west-3b",
"ZoneName": "eu-west-3c",
"ZoneName": "eu-west-2a", …
```
> updating region and availability zone constants

- troposphere/validators.py
fixes https://github.com/cloudtools/troposphere/issues/1822
[`AWS::SSM::PatchBaseline.OperatingSystem`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-patchbaseline.html#cfn-ssm-patchbaseline-operatingsystem)
> AWS::SSM::PatchBaseline.OperatingSystem AllowedValues expansion

- troposphere/kinesis.py
Aligning to AWS CFN Docs.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesis-stream.html#cfn-kinesis-stream-shardcount
> AWS::Kinesis::Stream.ShardCount required

- troposphere/kinesisanalyticsv2.py
- troposphere/validators.py
introduced in https://github.com/cloudtools/troposphere/commit/070f63c13aacf2effb47afe080d70e2813b0048b, https://github.com/cloudtools/troposphere/pull/1823
> Flake8 fixes

- troposphere/cloudfront.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-trustedkeygroups
> AWS::CloudFront::Distribution.CacheBehavior.TrustedKeyGroups

- troposphere/ecs.py
[AWS::ECS::Service](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html) => [DeploymentConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentconfiguration.html#cfn-ecs-service-deploymentconfiguration-deploymentcircuitbreaker) => [AWS::ECS::Service DeploymentCircuitBreaker](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-deploymentcircuitbreaker.html)
> Adding DeploymentCircuitBreaker property for ECS Service

- examples/Metadata.py
`add_metadata` is deprecated, switch to `set_metadata` instead
> docs: use Template.set_metadata instead of add_metadata

- troposphere/appconfig.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-hostedconfigurationversion.html
> Add support for AppConfig Hosted Configuration Version

- scripts/cfn2py
> Create Export instances for Output.Export in cfn2py

- troposphere/apigatewayv2.py
> AWS::ApiGatewayV2::Integration.IntegrationSubtype

- troposphere/constants.py
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.SupportAurora
> Add constants for RDS instance types: R6G

- troposphere/serverless.py
Add parameter per docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-minimumcompressionsize
> Add compression parameter

- troposphere/serverless.py
Add parameters as documented here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-sns.html
> Add new sns event parameters

- troposphere/apigateway.py
> Fix CanarySettings PercentTraffic definition

- troposphere/networkfirewall.py
- Added Property type for FirewallPolicy
- Added Property type for RuleGroup
- Added validation for RuleGroup.Type
> Fix for https://github.com/cloudtools/troposphere/issues/1933

- tests/test_elasticloadbalancerv2.py
- troposphere/elasticloadbalancingv2.py
> AWS::ElasticLoadBalancingV2::TargetGroup.TargetType

- troposphere/rds.py
See [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot)
> Added CopyTagsToSnapshot to DBCluster

- troposphere/ecs.py
Added ecs.TaskDefinition.RuntimePlatform as per 
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-runtimeplatform
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-runtimeplatform.html
> Added ecs.TaskDefinition.RuntimePlatform

- troposphere/serverless.py
Per [developer guide](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html#sam-layerversion-compatiblearchitectures)
> Added CompatibleArchitectures to LayerVersion

- troposphere/kinesis.py
- troposphere/validators.py
Added Kinesis StreamModeDetails per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kinesis-stream-streammodedetails.html
> Update Kinesis per 2021-12-09

- setup.cfg
Adding missing package for validators
> Adding missing package

- troposphere/serverless.py
Adds support for Serverless transform EphemeralStorage option per docs: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
> Add ephemeral storage

- troposphere/serverless.py
Added AWS::Serverless::StateMachine to serverless.py
> Added AWS::Serverless::StateMachine

- tests/test_serverless.py
- troposphere/serverless.py
> Add support for FunctionUrlConfig in Serverless Function

- tests/test_rds.py
- troposphere/validators/rds.py
> Allow RDS storage for sqlserver to have a minimum of 20GB

- .github/workflows/tests.yml
- setup.cfg
released on 2022-10-24, see https://pythoninsider.blogspot.com/2022/10/python-3110-is-now-available.html
> Run tests against Python 3.11 and add trove classifier

- .github/workflows/maintenance.yaml
- .github/workflows/tests.yml
This fixes deprecation warnings
> Use the latest github actions

- troposphere/validators/rds.py
update the RDS custom types for the validator:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html
> update engine types validator for AWS::RDS::DBInstance

- troposphere/validators/batch.py
Add support for the new Compute environment Allocation strategy SPOT_PRICE_CAPACITY_OPTIMIZED.
More info here https://docs.aws.amazon.com/batch/latest/userguide/allocation-strategies.html
> Batch validator add support for SPOT_PRICE_CAPACITY_OPTIMIZED

- troposphere/__init__.py
> add new DeletionPolicy attribute option, RetainExceptOnCreate

- tests/test_parameters.py
- troposphere/__init__.py
> Fix Parameters.validate incorrect validate for CommaDelimitedList

- troposphere/validators/kinesisanalyticsv2.py
Issue #2265
Updated the list of kinesisanalyticsv2 VALID_RUNTIME_ENVIRONMENTS
> Update kinesisanalyticsv2 VALID_RUNTIME_ENVIRONMENTS

- troposphere/validators/organizations.py
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-policy.html#cfn-organizations-policy-type
> Validate missing AWS Org policy types

- troposphere/serverless.py
> add MSKEvent params for serverless lambda esm
